### ISSUE TITLE
Upgrade instructions

### ISSUE THREAD

**Issue by jachin84** [pluralsight/PS-AutoLab-Env#103]
I couldn't find any upgrade instructions anywhere. Looking at the scripts it looks like you can safely run the setup process again to do an upgrade, is this correct?

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
