### ISSUE TITLE
Win Server 2016 Gui Install?

### ISSUE THREAD

**Issue by mgrayteco** [pluralsight/PS-AutoLab-Env#113]
Curious if there is a value to set to determine the Win Server 2016 install to have the management shell or gui?  

Is it a change in the ISO that is being downloaded or maybe even a value in the configuration files?

**Comment by jdhitsolutions** [comment]
I don't know off the top of my head but I'm sure there is a Lability setting. Perhaps @theJasonHelmick knows.

**Comment by mgrayteco** [comment]
Thanks for the input - the issue was the main VHDK was corrupt.  Removed and ran again with success.
