### ISSUE TITLE
Requires Dism ver 10

### ISSUE THREAD

**Issue by ghost** [pluralsight/PS-AutoLab-Env#116]
I have an error that says it needs Dism ver 10 or later installed but I have version 10.0.15063.0

**Comment by Absent2Day** [comment]
Looks not to be an issue with PS-AutoLab-Env but actually with Lability (which is also on GitHub).
There was a recent update to Lability which adds a DISM version check - here:

https://github.com/VirtualEngine/Lability/commit/8949ae4f5aae41074c6f05c8054a9a666315e69f

But the update seems to have broken it for systems running Windows 10 
(I have tried and found it to work without issue in Windows Server 2016)

An issue has been raised by someone already - here:

https://github.com/VirtualEngine/Lability/issues/247

**Comment by Absent2Day** [comment]
This should now be fixed with the update they provided - here:

https://github.com/iainbrighton/Lability/commit/dae6fb6aa16368124acb6165ab7ae8b78600ac3e
