### ISSUE TITLE
How to install lab with Win2k12 R2 Server instead of Win2k16 Servers

### ISSUE THREAD

**Issue by KbjYoda** [pluralsight/PS-AutoLab-Env#118]
I see the lab installs win2k16 servers and Win10 Clients, but I need a lab with Win2K12 R2 Servers. How can this be done?

**Comment by jdhitsolutions** [comment]
You would need to modify the configuration data file to point to Windows 2012 R2 servers.  The challenge might be finding an eval ISO that you can download. And to be honest, I haven't tested the convert iso to VM script to see if it works with 2012.
