### ISSUE TITLE
unattend-lab errors out at creating VM

### ISSUE THREAD

**Issue by rxmurillo** [pluralsight/PS-AutoLab-Env#120]
Getting the following error, however I can create a VM through UI or one line command with no problems, please advice?

New-VM : Hyper-V encountered an error trying to access an object on computer 'COMPUTER' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.10.1\DSCResources\xHyper-V\DSCResources\MSFT_xVMHyperV\MSFT_xVMHyperV.psm1:350 char:21
+             $null = New-VM @parameters
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.NewVM

**Comment by rxmurillo** [comment]
Currently running Windows 10 version 1703

$PSVersiontable
Name                           Value
----                           -----
PSVersion                      5.1.15063.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by jdhitsolutions** [comment]
What configuration are you trying to run?

**Comment by jdhitsolutions** [comment]
Make sure you are running in an elevated PowerShell session.

**Comment by terrypen** [comment]
I have been getting tons of errors that are very similar to the one you have gotten, not exact but similar! I just "fixed" my errors.
1. Uninstall the Lability module by either running `Remove-Module -Name Lability` or by running `Get-Module -Name Lability -ListAvailable` and noting the directory for the Lability 0.10.1 and using file manager to delete the directory (maybe move it to temp folder.)
2. Install the latest Lability by running `Install-Module Lability` and make sure it is installing 0.15 or higher.
3. Run either `Unattend-Lab` or the three commands per the Instructions.md file located in the Configurations folder.

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
