### ISSUE TITLE
How long for tests?

### ISSUE THREAD

**Issue by razaice** [pluralsight/PS-AutoLab-Env#125]
I've read that the tests for the VMs are supposed to take 30-60 minutes, but mine ran for over three hours before I gave up on it.  This is the screen that kept popping up every five minutes:

https://imgur.com/XIQ3mGr

Is this what's supposed to be happening?  If I wait long enough, will the tests complete?

**Comment by jdhitsolutions** [comment]
Take a look at https://github.com/theJasonHelmick/PS-AutoLab-Env/issues/126

**Comment by jdhitsolutions** [comment]
To help us troubleshoot it would also help us to know what configuration you are trying to run, whether you are on Windows 10 or Server 2016 and the contents of $PSVersiontable.

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
