### ISSUE TITLE
Setup-Lab fails on Windows 2016

### ISSUE THREAD

**Issue by deccie** [pluralsight/PS-AutoLab-Env#129]
When performing Setup-Lab I receive the following error:

PSDesiredStateConfiguration\user : A duplicate resource identifier '[User]administrator' was found while processing
the specification for node 'Win10Ent'. Change the name of this resource so that it is unique within the node
specification.
At D:\autolab\Configurations\Windows10\VMConfiguration.ps1:49 char:10
+          user $env:username {
+          ~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : DuplicateResourceIdInNodeStatement,PsDesiredStateConfiguration\User

Compilation errors occurred while processing configuration 'AutoLab'. Please review the errors reported in error
stream and modify your configuration code appropriately

This is a fatal error and the VMs are not created.  How would I get past this to complete the install?

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
