### ISSUE TITLE
Please remove installers from your repo history

### ISSUE THREAD

**Issue by csharmath** [pluralsight/PS-AutoLab-Env#131]
I've just cloned this repo and saw that it's almost like 200Mb, so I've burned like 20cents on just cloning from a mobile hotspot. No big deal but were just curious to see what's inside and found 2 RSAT instsallers in the history
96800972 Resources/WindowsTH-RSAT_WS2016-x64.msu
95388388 Resources/WindowsTH-RSAT_TP5_Update-x64.msu

by running this
$ git rev-list Dev | while read rev; do git ls-tree -lr $rev | cut -c54- | grep -v '^ '; done | sort -u | perl -e '
  while (<>) {
    chomp;
    @stuff=split("\t");
    $sums{$stuff[1]} += $stuff[0];
  }
  print "$sums{$_} $_\n" for (keys %sums);
' | sort -rn >> large_files.txt

which was used from here 
http://blog.jessitron.com/2013/08/finding-and-removing-large-files-in-git.html

Wanna use something like this probably
https://stackoverflow.com/questions/872565/remove-sensitive-files-and-their-commits-from-git-history

Thanks

**Comment by theJasonHelmick** [comment]
Thank you!!  I hadn't;t noticed and I really appreciate you pointing this out.  I will get that fixed. We are working on a new version that will be released by year end thats in a different repo.....so I will check and clean that one as well.  Again, thank you!
