### ISSUE TITLE
Please help ... 

### ISSUE THREAD

**Issue by dvprao** [pluralsight/PS-AutoLab-Env#132]
A request from a  "NewBie"

I wish there is some kind of logging so that one can look at it to see what could be missing ...
This 5 minutes wait is very "blackbox" like
I think this is an Error that is stopping the setup .:
( My Hyper-v Manager is empty .

New-VMSwitch : Failed while creating virtual Ethernet switch.
Switch create failed, name = 'FFB8E8DC-E335-4B2E-A38E-7CB8689C3279', friendly name = 'LabNet': Not found (0x80041002).
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.12.4\DSCResources\xHyper-V\DSCResources\MSFT_xVMSwitch\MSFT_xV
MSwitch.psm1:156 char:21
+             $null = New-VMSwitch @parameters
+                     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-VMSwitch], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.NewVMSwitch

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
