### ISSUE TITLE
PS-AutoLab-Env-3.0.2

### ISSUE THREAD

**Issue by ppatel61** [pluralsight/PS-AutoLab-Env#135]
This is the issue I am getting and I am not sure how to fix it. Here is a screenshot 
![image](https://user-images.githubusercontent.com/34921046/34418721-13c3633a-ebc5-11e7-83f8-c46f102b1a21.png)

Please help 

Thanks

**Comment by jdhitsolutions** [comment]
What version of Windows are you running?

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
