### ISSUE TITLE
Remove and Refresh

### ISSUE THREAD

**Issue by jdhitsolutions** [pluralsight/PS-AutoLab-Env#137]
We think part of the challenges people are facing are related to changes that creep in over time with Windows, Hyper-V and the Lability module.  This is especially true if you run `Get-Module Lability -list` and see a version newer than 0.10.1. Sometimes the best course of action is to wipe out and start all over again.

To do that you need to make sure you aren't using any Autolab configurations. If you are, change to the configuration folder in PowerShell and run Wipe-Lab. 

The rest of the process, which you should be able to do manually is as follows:
+ In PowerShell run `get-module lability -list | uninstallmodule`
+ In PowerShell run `del 'c:\program files\windowspowershell\modules\psautolab' -force -recurse`
+ In PowerShell run `remove-vmswitch -force` . If you've already removed this when wiping a lab you might get an error. 
+ In PowerShell run `get-netnat labnat | remove-netnat ` Answer Y to confirm.
+ In PowerShell run `del c:\autolab -recurse -force` or use Windows Explorer
+ Reboot you computer to clear any caching
+ Start the setup process again with the latest version of this module.

**Comment by fjvasquez** [comment]
One thing that worked for me, besides following jeff's steps was to remove all the dsc resources too.
`get-module x* | uninstall-module`
Then start installing the resources with the version number that is shown in the errors when running unattend-lab, until there is no more errors.

**Comment by spieter** [comment]
I ran into the same error. For me it was solved by removing my install media. It was also the evaluation version of server 2016. I think it got screwed up by the same volume name.
