### ISSUE TITLE
Unable to extract file

### ISSUE THREAD

**Issue by itsmattdee** [pluralsight/PS-AutoLab-Env#142]
I'm unable to extract the file to my C: drive due to the error I've attached via screenshot. Each time I try to continue it tries to extract but comes back that the data is corrupt. Any thoughts?
![unable to extract](https://user-images.githubusercontent.com/36854518/36679544-5f55f7fc-1b0b-11e8-95cf-4087c1aed29e.PNG)

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
