### ISSUE TITLE
Unable to connect to the internet

### ISSUE THREAD

**Issue by embee2192** [pluralsight/PS-AutoLab-Env#143]
**I am unable to get connectivity to the internet.  I haven't tweaked the ip or dns.** 

![image](https://user-images.githubusercontent.com/36834130/36706265-32702200-1bbd-11e8-9815-578adf01058e.png)

Would having internal network selected be the cause? 

![image](https://user-images.githubusercontent.com/36834130/36706351-945ae860-1bbd-11e8-9883-8abf27d9ea99.png)

thanks,

Matt

**Comment by NLRemcoNL** [comment]
Open Powershell on the host and run "Get-NetNat"  
This is my output. 
![image](https://user-images.githubusercontent.com/28533124/41204093-6d8acc18-6ce0-11e8-8e9b-469552d03437.png)

**Comment by superdale007** [comment]
Make sure you have a ethernet port (that the script should have created) on the host machine that looks like this before running the "enable-internet" script.
![autolab-network](https://user-images.githubusercontent.com/18034473/50061018-ae07b000-0158-11e9-91f1-51814f242999.PNG)

**Comment by superdale007** [comment]
Also, make sure you're running the latest version of AutoLab (3.1.0)...and if you're trying to upgrade from version 3.0.x, I would do the following:

1. Run Wipe-lab.ps1.
2. Delete the contents in the following folders in the autolab directory
  a) Configurations and VMVirtualHardDisks...but leaving the other folder's content, you'll save yourself 
   the time of having to download the .iso's, and creating the MasterVirtualHardDisks all over again. 
 
3. Delete all the old resource modules from the c:\program files\windows PowerShell\Modules folder (PSAutolab, all the directories that start with "x" (like xDhcpServer) and I'd whack the Lability folder as well for good measures..
4. Delete the ethernet adapter called vEthernet (LabNet) if it's still there.
5. Then try rebooting and running your setup-host.ps1 (the new version again) again.

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
