### ISSUE TITLE
Checksum failed - how to change the download path

### ISSUE THREAD

**Issue by Silvermist78** [pluralsight/PS-AutoLab-Env#144]
Hi Jason,

I have been trying to setup this Autolab.  I get to a point where powershell starts to download the ISO from Microsoft.  It fails the checksum, as it's downloading a newer ISO.  Looking at the VMConfigurationData file - I thought I would download the correct ISO and copy it to the ISO folder (and renaming the ISO), however after running unattend-lab again, it still wants to download the newer ISO.

I have even tried editing the vmconfigurationdata file with the following:

## Desmond Uri = 'http://download.microsoft.com/download/1/6/F/16FA20E6-4662-482A-920B-1A45CF5AAE3C/14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO';
                    Uri ='file://G:\ISO\14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO';
                    Checksum = '18A4F00A675B0338F3C7C93C4F131BEB';

So I edited it such that it points to my g drive for the file.  And it still somehow starts to download from mircosoft.

So my question is - where do I change the download path, such that it looks at my g:drive.  Or where do I change the MD5 hash value to match the newer ISO version.

Thanks
Desmond

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, the ISO file will be downloaded to the ISOs folder under C:\Autoloab or where ever you put it.
