### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by Deyasoft** [pluralsight/PS-AutoLab-Env#148]
I have installed the AutoLab-Env but I don't have passwords to login virtual machines.
Thank you for your help.

**Comment by Foxman74** [comment]
Anybody know or know where I can find this info

**Comment by kderiger** [comment]
The are usually in the VMConfigurationData.psd1 of each configuration folder

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, the default password for just about everything is `P@ssw0rd`. Hardly secure and stored in plain text but these are lab and test systems.
