### ISSUE TITLE
Troubleshooting Setup issues using 'Jason-DSC-Env'

### ISSUE THREAD

**Issue by terrypen** [pluralsight/PS-AutoLab-Env#151]
I have been having numerous issues with getting any of the labs to run! 

My current issue: It seems that the `Validate-Lab` never finishes due to the N1 server not getting created.
 
I'm wondering if I have the correct ISO and/or the MasterVirtualHardDisk for it is corrupt as I copied from my original autolab folder. 
Which ISO is it supposed to be using (Microsoft ISO name and name in ISO folder)
What size is the .vhdx supposed to be for the Nano server?

[ADMIN]: PS C:\AutoLab\Configurations\Jason-DSC-Env> Invoke-Pester .\VMValidate.test.ps1
Describing DC1
 [+] [DC1] Should accept domain admin credential 304ms
 [+] [DC1] Should have feature AD-Domain-Services installed 540ms
 ....... (everything was good on DC1)
Describing S1
 [+] [S1] Should accept domain admin credential 371ms
 [+] [S1] Should have an IP address of 192.168.3.50 0.99s
 [+] [S1] Should have a DNS server configuration of 192.168.3.10 275ms
Describing S2
 [+] [S2] Should accept domain admin credential 505ms
 [+] [S2] Should have an IP address of 192.168.3.51 1.47s
 [+] [S1] Should have a DNS server configuration of 192.168.3.10 281ms
Describing PullServer
 [+] [S1] Should accept domain admin credential 459ms
 [+] [S1] Should have an IP address of 192.168.3.70 1.51s
 [+] [S1] Should have a DNS server configuration of 192.168.3.10 274ms
Describing NanoServer
 [-] [Nano] Should respond to WSMan requests 121ms
   ArgumentException: The input VMName N1 does not resolve to a single virtual machine.
   at <ScriptBlock>, C:\AutoLab\Configurations\Jason-DSC-Env\VMValidate.test.ps1: line 138
 [-] [Nano] Should have an IP address of 192.168.3.60 33ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, C:\AutoLab\Configurations\Jason-DSC-Env\VMValidate.test.ps1: line 143
 [-] [Nano] Should belong to the Workgroup domain 34ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, C:\AutoLab\Configurations\Jason-DSC-Env\VMValidate.test.ps1: line 148
 [-] [Nano] Should have the DSC package installed 28ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, C:\AutoLab\Configurations\Jason-DSC-Env\VMValidate.test.ps1: line 153
Describing Cli1
 [+] [CLI] Should accept domain admin credential 1.31s
 [+] [CLI] Should have an IP address of 192.168.3.100 947ms
 [+] [CLI] Should have a DNS server configuration of 192.168.3.10 603ms
Tests completed in 11.61s
Passed: 35 Failed: 4 Skipped: 0 Pending: 0 Inconclusive: 0

**Comment by terrypen** [comment]
Anyone monitoring these for possible work arounds/fixes?

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
This configuration has been updated beginning with v4 of this module.
