### ISSUE TITLE
AutoLab Error on creating VM's on Hyper-V

### ISSUE THREAD

**Issue by mitz1419** [pluralsight/PS-AutoLab-Env#152]
Hi Everyone,

I just bump on this issue, hope someone can advise resolving it. I've ran unattend-lab and then finish downloading and the error appears. I am using VMware Workstation Pro with Win10 Enterprise.

Please see attached screenshot.
![autolab error after download](https://user-images.githubusercontent.com/40743647/42138601-a28c417a-7db2-11e8-9322-66d0815906fb.JPG)
![autolab error after download2](https://user-images.githubusercontent.com/40743647/42138603-a5779e70-7db2-11e8-903b-d49f3ba71c85.JPG)

**Comment by dustinjclark** [comment]
I see the exact same issue using v3.1.0.4.  I'm running v1803 and not using VMWare.

**Comment by dustinjclark** [comment]
Same error on TEST-SingleDC as well.  There's something in LabVM.ps1 that it does not like.

**Comment by Defaqto** [comment]
I am getting these errors too. Has anyone found a resolution to this?

**Comment by CryptechFox** [comment]
Looks like this was resolved in [#150](https://github.com/theJasonHelmick/PS-AutoLab-Env/issues/150)
Run these two commands in powershell before running the script:

Register-LabMedia -force -Id "2016_x64_Standard_EN_Eval" -MediaType "ISO" -Uri 'C:\AutoLab\ISOs\2016_x64_EN_Eval.iso' -Architecture 'x64' -Description 'Windows Server 2016 Standard Evaluation (Desktop Experience)' -ImageName 'Windows Server 2016 Standard Evaluation (Desktop Experience)' -Filename '2016_x64_EN_Eval.iso'

Register-LabMedia -force -Id "2016_x64_Standard_Core_EN_Eval" -MediaType "ISO" -Uri 'C:\AutoLab\ISOs\2016_x64_EN_Eval.iso' -Architecture 'x64' -Description 'Windows Server 2016 Standard Evaluation' -ImageName 'Windows Server 2016 Standard Evaluation' -Filename '2016_x64_EN_Eval.iso'

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, VMWare Workstation is not officially supported at this time.
