### ISSUE TITLE
unattend-setup

### ISSUE THREAD

**Issue by Jusatec** [pluralsight/PS-AutoLab-Env#154]
Installing required DSCResource modules from PSGallery
You may need to say "yes" to a Nuget Provider
Build the .Mof files from the configs

    Directory: C:\AutoLab\Configurations\devops-powershell-fundamentals

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        7/12/2018   3:10 PM         525930 DC1.mof
-a----        7/12/2018   3:10 PM           1110 DC1.meta.mof
-a----        7/12/2018   3:10 PM           8424 S1.mof
-a----        7/12/2018   3:10 PM           1108 S1.meta.mof
-a----        7/12/2018   3:10 PM           8424 S2.mof
-a----        7/12/2018   3:10 PM           1108 S2.meta.mof
-a----        7/12/2018   3:10 PM          13768 Cli1.mof
-a----        7/12/2018   3:10 PM           1112 Cli1.meta.mof
Building the lab environment
Host configuration test failed and may have a pending reboot.
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.10.1\Src\LabConfiguration.ps1:228 char:13
+             throw $localized.HostConfigurationTestError;
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Host configurat...pending reboot.:String) [], RuntimeException
    + FullyQualifiedErrorId : Host configuration test failed and may have a pending reboot.

**Comment by Jusatec** [comment]
Name                           Value
----                           -----
PSVersion                      5.1.14393.187
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.187
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by Jusatec** [comment]
I was reviewing other users issue's "Will I be able to do this install if I have Windows 10 Home version"

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, it is unlikely this module will ever work on Windows 10 home. If you can't run `Get-DSCResource`  this module will never work.
