### ISSUE TITLE
Stuck at New-NetNat : A parameter cannot be found that matches parameter name 'InternalIPInterfaceAddressPrefix'.

### ISSUE THREAD

**Issue by theweazel** [pluralsight/PS-AutoLab-Env#156]
My Lab install wont go past tests, I get the  following error:

New-NetNat : A parameter cannot be found that matches parameter name 'InternalIPInterfaceAddressPrefix'.
At C:\Program Files\WindowsPowerShell\Modules\PSAutoLab\PSAutolab.psm1:204 char:31
+ ...   New-NetNat -Name $NatName -InternalIPInterfaceAddressPrefix $NatNet ...
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-NetNat], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-NetNat

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
