### ISSUE TITLE
Windows Server DHCP 2016 - pending reboot issue

### ISSUE THREAD

**Issue by tytanowyJohnny** [pluralsight/PS-AutoLab-Env#157]
Hello,

I was trying to setup Windows Server DHCP 2016 VM from AutoLab but after running "unattend-lab" or "setup-lab" I get error message saying that there is a pending reboot.

Well, there is no pending reboot - I have already re-booted my computer couple of times.

I was able to setup Windows10 lab environment without any issues but I need AD.

![capture](https://user-images.githubusercontent.com/33232884/44111042-a9aa6b50-a001-11e8-98b4-c3bb07a757a4.PNG)

**Comment by simon-scs** [comment]
The is an issue in older versions of Lability. Run the following and you should be sweet -
`Update-Module -Name Lability`

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, the pending reboot problem was a Lability bug which has since been fixed.  Use v4 or later of this module.
