### ISSUE TITLE
Checksum Error

### ISSUE THREAD

**Issue by gtiddiman** [pluralsight/PS-AutoLab-Env#158]
I am getting a checksum error right at the end of downloading the Windows10.iso:
Resource download 'C:\AutoLab\ISOs\WIN10_x64_ENT_RS4_EN_Eval.iso' checksum does not match
'89F6B3079B3669560D29F3C4BE9CC74D'.
At line:59 char:13
+             throw ($localized.ResourceChecksumMismatchError -f $Desti ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Resource downlo...9F3C4BE9CC74D'.:String) [], RuntimeException
    + FullyQualifiedErrorId : Resource download 'C:\AutoLab\ISOs\WIN10_x64_ENT_RS4_EN_Eval.iso' checksum does not matc
   h '89F6B3079B3669560D29F3C4BE9CC74D'.

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
