### ISSUE TITLE
Validate-Lab never completes

### ISSUE THREAD

**Issue by tj76352** [pluralsight/PS-AutoLab-Env#160]
I have tried to complete the lab environment setup for going on a week now; tried on Windows 10 Pro, Enterprise, Server 2016, and they all fail the validation portion and/or DC1 never fully boots (hung on login service when attempting to connect in Hyper-V on all three setup attempts). I have left the validation going overnight and it still does not complete.

Any suggestions or help would be greatly appreciated!

**Comment by ChrisLGardner** [comment]
Can you stop the VM and then start it again, it should then come back up to a login screen. If you log in there should be a folder called Bootstrap on the root of C:\ and it should have a log file in there for you look through. It should jump out if there are any errors in the provisioning process.

**Comment by tj76352** [comment]
I was able to stop the DC1 VM and start it again, but it hung in the same spot and would not allow login.

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, sometimes the best solution is to wipe the lab and start all over. DSC configurations can fail sometimes for unexplained reasons. I've built lab configurations that appear to get hung yet work just fine after wiping and restarting the process.
