### ISSUE TITLE
Start-VM : Hyper-v was unable to find virtual machine, Any suggestion?

### ISSUE THREAD

**Issue by rajinder999** [pluralsight/PS-AutoLab-Env#164]
![image](https://user-images.githubusercontent.com/45180903/48806452-75013900-ed6e-11e8-9834-9905faf75dc2.png)

**Comment by MCKPRO** [comment]
I get the same ERROR!

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
