### ISSUE TITLE
Error / Warning during installation

### ISSUE THREAD

**Issue by jbaileydba** [pluralsight/PS-AutoLab-Env#166]
Received this error when installing by version 3.0.4 and 3.1.1:

Starting to Initialize host and install Hyper-V
WARNING: [4:12:19 PM] DSC resource 'Test-WindowsOptionalFeatureTargetResource' failed with errror 'An attempt was made
to load a program with an incorrect format.
'.
Starting to Initialize host and install Hyper-V
WARNING: [4:12:20 PM] DSC resource 'Test-WindowsOptionalFeatureTargetResource' failed with errror 'An attempt was made
to load a program with an incorrect format.
'.
WARNING: [4:12:20 PM] DSC resource 'Set-WindowsOptionalFeatureTargetResource' failed with errror 'An attempt was made
to load a program with an incorrect format.
'.
Get-ChildItem : Cannot find path 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto
Update\' because it does not exist.
At C:\Program Files (x86)\WindowsPowerShell\Modules\Lability\0.10.1\DSCResources\xPendingReboot\DSCResources\MSFT_xPend
ingReboot\MSFT_xPendingReboot.psm1:24 char:27
+ ... dateKeys = (Get-ChildItem 'hklm:SOFTWARE\Microsoft\Windows\CurrentVer ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKEY_LOCAL_MACH...te\Auto Update\:String) [Get-ChildItem], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
