### ISSUE TITLE
Install issue with DISM import-module

### ISSUE THREAD

**Issue by Kermitneedshelp** [pluralsight/PS-AutoLab-Env#168]
I get this error in Powershell when trying to run setup-host.ps1

Installing PSAutoLab Module for the lab build
Import-Module : Cannot bind argument to parameter 'Name' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.10.1\Lib\Dism.ps1:63 char:43
+         $dismModule = Import-Module -Name $dism -Force -Scope Global  ...
+                                           ~~~~~
    + CategoryInfo          : InvalidData: (:) [Import-Module], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ImportModul
   eCommand

ConfigurationPath       : C:\AutoLab\Configurations
DifferencingVhdPath     : C:\AutoLab\VMVirtualHardDisks
HotfixPath              : C:\AutoLab\Hotfixes
IsoPath                 : C:\AutoLab\ISOs
ModuleCachePath         : C:\ProgramData\Lability\Modules
ParentVhdPath           : C:\AutoLab\MasterVirtualHardDisks
ResourcePath            : C:\AutoLab\Resources
ResourceShareName       : Resources
DisableLocalFileCaching : False
EnableCallStackLogging  : False
DismPath                :

GetDscModule : DSC module\resource 'PSDesiredStateConfiguration\MSFT_WindowsOptionalFeature' not found.
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.10.1\Lib\DscResource.ps1:37 char:33
+ ... ourcePath = GetDscModule -ModuleName $ModuleName -ResourceName $Resou ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,GetDscModule

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, the minimum supported Lability version is 0.18.0 as of v4.0.0 of this module.
