### ISSUE TITLE
Win10Ent Failing Validation

### ISSUE THREAD

**Issue by fitzevan** [pluralsight/PS-AutoLab-Env#169]
I'm trying to setup the Windows 10 lab, and all goes well until the validation, and it gets stuck.  Looking at the log referenced in another post it appears the VM is waiting for a reboot, i have however rebooted it several times. So i'm kinda stuck as to what to do.

Any thoughts? thanks in advanced for the help

[Bootstrap-20190130-100437.log](https://github.com/theJasonHelmick/PS-AutoLab-Env/files/2814351/Bootstrap-20190130-100437.log)

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
