### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by jaswicki** [pluralsight/PS-AutoLab-Env#170]
When I watched Jason's video about this concept I couldn't wait to try it out. Sadly it has been an exercise in frustration. I have been slowly going through the code, fixing errors but I still haven't had a successful run. 

I have cleaned up a bunch of problems when running Setup-lab but it still won't even create the Mofs. Error is Cannot resolve the path .\*.psds1' to a single .psd1 file. 

Is this dead? What did Microsoft change that made this unworkable? I was really anticipating the suggested Azure Autolab but I haven't seen anything on that either. Can anyone point to a working resource for the autolab concept?

**Comment by TWisch** [comment]
you need to switch the path from where you start the setup-lab. You need to be in the path which contains the config. Still. most of the configs are not working anymore cause the needed module labibility is not working properly anymore.

**Comment by jaswicki** [comment]
Thanks for the reply. That is a shame though as I think the concept is great. Any idea if the anticipated Azure version will ever be developed?

**Comment by TWisch** [comment]
Sorry but I do not know. I think problem with this Lab here are to many dependencys to windows, powershell and other modules. Tried to find errors and fix them, got only frustrated by more and more errors...

**Comment by MCKPRO** [comment]
It look like this Project is Dead.
No one is answering any question.

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
