### ISSUE TITLE
ISO download fail and no VM's are populated in Hyper-V

### ISSUE THREAD

**Issue by ArielRamirez99** [pluralsight/PS-AutoLab-Env#171]
This keeps populating whenever I run unattend-lab

![screenshot 96](https://user-images.githubusercontent.com/40073214/53281824-cd383600-36e3-11e9-8950-6b95e8cb29df.png)

**Comment by ArielRamirez99** [comment]
I already had Hyper-V installed before this set up. Is that a problem?

**Comment by TWisch** [comment]
Nope same Problem here. To many dependencies are the Problem, some of the Commands changed... so the script is not working properly anymore. Tried to fix but no chance more and more bugs and errors...

**Comment by jcklinger** [comment]
Same issue here, it starts the download of the server ISO and quits at about 700,000bytes

**Comment by jcklinger** [comment]
I 

> Same issue here, it starts the download of the server ISO and quits at about 700,000bytes

**Comment by AFKxtoday** [comment]
Make sure you are running Windows Enterprise ;)

https://www.howtogeek.com/250503/how-to-upgrade-to-windows-10-enterprise-without-reinstalling-windows/

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, this module should work just fine on Windows 10 Pro running PowerShell 5.1. Remove any previous versions of PSAutolab and start all over with the latest version of this module.
