### ISSUE TITLE
any work around for Hyper-V installation on Windows10 Home?

### ISSUE THREAD

**Issue by tcn84** [pluralsight/PS-AutoLab-Env#172]
Understood that Enterprise, Pro and Education version required for HyperV in Windows10, I am just wondering if any work around for the Home version? AutoLab ran quickly with the warning below, configuration files downloaded fine but none Hyper-V files. If no work around then it may be good to mention of Hyper-V requirement.

WARNING: DSC resource 'Set-WindowsOptionalFeatureTargetResource' failed with errror 'Feature name Microsoft-Hyper-V-All is unknown

**Comment by TWisch** [comment]
You can try to look it up manualy. But I don't think this will work. 
Systemconfiguration->Programs and features->on the left side Windows-features. If you can not find it there, it will not be possible to install it as far as I know.

**Comment by AFKxtoday** [comment]
Make sure you are running Windows Enterprise ;)

https://www.howtogeek.com/250503/how-to-upgrade-to-windows-10-enterprise-without-reinstalling-windows/

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, this module probably will never work on Windows 10 Home as it most likely lacks DSC support. If you can't run `Get-DSCResource` this module will never work for you.
