### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sanjeevsv** [pluralsight/PS-AutoLab-Env#173]
Hi,

I am new to powershell and while setting up the required lab. I hit the following error. Can anyone assist me on the configuration and installation of this lab:

![image](https://user-images.githubusercontent.com/25172062/56466818-770e1780-6434-11e9-8903-ac51171be413.png)

Regards,
Sanjeev S V

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
If you have TrustedHosts configured by GroupPolicy, this module will probably fail. There is an enhancement request for better management of the TrustedHosts setting. For now, you could try removing the old version of PSAutolab and install the new version from the PowerShell Gallery.
