### ISSUE TITLE
Unattend-lab vmvalidate-lab failed  for powershelllab-0.9.4

### ISSUE THREAD

**Issue by tititech** [pluralsight/PS-AutoLab-Env#175]
The script is keep failing when running the VMvalidate.test.ps1. 

I run the unattend-lab -ignorePendingReboot.  The script created one vm already but it stopped at vmvalidation step.

I am running it on win 10 ent 10.0.18.362 build 18362

![autolab4](https://user-images.githubusercontent.com/36680634/58037209-c3a34c00-7ae1-11e9-8e95-db3ded1b9ee2.PNG)

![image](https://user-images.githubusercontent.com/36680634/58037275-e6356500-7ae1-11e9-9d53-995d0ead23f9.png)

![image](https://user-images.githubusercontent.com/36680634/58036803-cf424300-7ae0-11e9-8260-4a937269dfec.png)

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
for future reference, you must have an execution policy that allows running scripts. This configuration has also been updated beginning with v4.0.0.
