### ISSUE TITLE
ImportClassResourcesFromModule : Exception calling "ImportClassResourcesFromModule"

### ISSUE THREAD

**Issue by MCKPRO** [pluralsight/PS-AutoLab-Env#176]
I keep getting this error now

![Get-DscResource](https://user-images.githubusercontent.com/41348549/58111874-23175f80-7ba7-11e9-983f-1d9447eaa8c5.png)

**Comment by MCKPRO** [comment]
It look like this Project is Dead.
No one is answering any question.
I get to many ERRORS.

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
