### ISSUE TITLE
Failure to download .ISO - FIXED

### ISSUE THREAD

**Issue by AFKxtoday** [pluralsight/PS-AutoLab-Env#178]
If you receive a "pending reboot" error when running 'Unattend-Lab', the problem may be that you are not running Windows Enterprise. If this is the case, upgrade, rerun 'setup-host.ps1' and 'Unattend-Lab".

https://www.howtogeek.com/250503/how-to-upgrade-to-windows-10-enterprise-without-reinstalling-windows/

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, this module should work on Windows 10 Pro or Enterprise. The previous version of the module had outdated ISO settings Follow the instructions to remove any old versions, install the new version from the PowerShell Gallery and try again. If there are still problems, please post a new issue.
