### ISSUE TITLE
Fails to download the Server ISO

### ISSUE THREAD

**Issue by jay33stone** [pluralsight/PS-AutoLab-Env#179]
Please see the error message. 

![image](https://user-images.githubusercontent.com/53451681/62084671-ad66ea00-b20e-11e9-8104-8e736543aaf9.png)

I have verified that I'm on the Win10 Enterprise version. This is a physical machine, and I have adjusted the power setting to high performance. I have watched the download happen 3 times, and seems to not get all the bits. when I go back and check to see the ISO's you can see that not all the bits are there.
![image](https://user-images.githubusercontent.com/53451681/62084649-9d4f0a80-b20e-11e9-8c22-17108eb2fb10.png)

please advise as to a possible solution.

Thanks,
Jay

**Comment by jay33stone** [comment]
I'm going to try and run the setup-lab instead of the unattend.lab and see if that makes any difference.
Also, I do some digging on the error, and on line 357 char 27 all looks good, but maybe someone can take a look.

**Comment by bvi1998** [comment]
I have the same problem. I was able to download it a couple of days ago, but deleted the environment due to other issues so I no longer have it.

**Comment by jay33stone** [comment]
When can we expect to see an answer to this issue, or at least an acknowledgement that this is an issue.

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
For future reference, this configuration has been marked as obsolete, although we may need to build a replacement. Follow the instructions to remove any old versions of the module, install the new version from the PowerShell Gallery and try again. If you still run into problems, then please post a new issue.
