### ISSUE TITLE
Downloading issues

### ISSUE THREAD

**Issue by KarimAlpha** [pluralsight/PS-AutoLab-Env#193]
Dear all,
I am trying to create a new test lab for one of our projects.
However, I am struggling to download the different files.
We are behind the company's proxy that makes it impossible for Administartor users to download microsoft images.

Is it an option to do a manual download of all necessary files in advance?
Many thanks in advance for your help!

Cheers
Karim

**Comment by jdhitsolutions** [comment]
You can manually download the ISO files and put them in the Autolab\ISOs directory. You can use the `Get-Labmedia` cmdlet from the Lability module to find the download link.

```powershell
get-labmedia | select id,filename,uri
```

Be sure to save the file using the filename.

**Comment by jdhitsolutions** [comment]
You might have an issue with DSC Resources as well. In which case you'll have to look at the pds1 file to see what DSC resources you need to download and install.

**Comment by jdhitsolutions** [comment]
Invoke-Webrequest has proxy related parameters so you could do something like this:

```powershell
$nano = get-labmedia -id 2016_x64_standard_nano_EN_eval
Invoke-WebRequest -uri $nano.uri -OutFile c:\autolab\isos\$nano.filename -proxy <value> -proxycredential <value>
```

**Comment by jdhitsolutions** [comment]
Don't forget to run the checksum on your download.

**Comment by KarimAlpha** [comment]
Hello jdhitsolutions,
Thanks a Million for your quick answer!
I will try this immediately!
I cant wait to have my first virtual lab!

Cheers
Karim

**Comment by jdhitsolutions** [comment]
Let me know if this works so I can close this issue.

**Comment by KarimAlpha** [comment]
Please feel free to close the issue...many thanks for your help!
