### ISSUE TITLE
Problems running Pester script after install

### ISSUE THREAD

**Issue by CarltonW** [pluralsight/PS-AutoLab-Env#195]
I went through the manual process then run the pester script and got an error about the "Show" parameter. I'm running this on Windows 10 (1903) with HyperV. Here is my current version and the error:

> PS C:\autolab\Configurations\Implement-Windows-Server-DHCP-2016> Get-PSAutolabSetting

PSVersion : 5.1.18362.145
Edition   : Desktop
OS        : Microsoft Windows 10 Enterprise
PSAutolab : 4.2.0
Lability  : 0.18.0
Memory    : 16680388

> Invoke-Pester : A parameter cannot be found that matches parameter name 'Show'.
At C:\Program Files\WindowsPowerShell\Modules\PSAutoLab\4.2.0\functions\public.ps1:478 char:49
+         $test = Invoke-Pester -Script $testpath -Show none -PassThru
+                                                 ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Pester], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Invoke-Pester

**Comment by jdhitsolutions** [comment]
I bet you are running an old version of Pester. If you run get-module pester -listavailable and only see v3.4 or something like that you need to install a newer version. The old version ships with Windows so you can't run Update-Module. You will need to use Install-Module.

**Comment by CarltonW** [comment]
That was it. Thanks for this test lab.

**Comment by jdhitsolutions** [comment]
I need to update the install process to make sure the latest version of Pester is installed. Saving this as an open issue and work item.

**Comment by CarltonW** [comment]
Thanks for providing this test environment!

**Comment by jdhitsolutions** [comment]
This should be better handled in v4.3.0
