### ISSUE TITLE
After Wipe-Lab, have to run Setup-Lab multiple times

### ISSUE THREAD

**Issue by montge** [pluralsight/PS-AutoLab-Env#200]
After running `Wipe-Lab` it appears that on Windows 10 Pro we need to re-run the command to create the hosts. Possible race condition issue. Fails as below, but after running 4 times it appears the hosts get created.

```
Failed to start lab configuration.
Set-LabVMDiskFileResource : Cannot bind argument to parameter 'VhdDriveLetter' because it is an empty string.
At line:82 char:74
+ ... MDiskFileResource @PSBoundParameters -VhdDriveLetter $vhdDriveLetter;
+                                                          ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-LabVMDiskFileResource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Set-LabVMDiskFileResource
```

**Comment by jdhitsolutions** [comment]
That's tough to troubleshoot and not something I've seen before. You might try rebooting after running Wipe-Lab and verifying that the VMs have been removed. If this is still an issue or something you can provide reproducible steps, let me know and include the results of Get-PSAutolabSetting.
