### ISSUE TITLE
DC not setting up

### ISSUE THREAD

**Issue by alexjriggs** [pluralsight/PS-AutoLab-Env#202]
Trying to setup the PowerShellLab in the Autolab configurations all the VM's setup execept the DC I keep getting these errors.

The term 'Get-ADDomain' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-ADDomain:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : DOM1

The term 'Get-ADorganizationalUnit' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-ADorganizationalUnit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : DOM1

The term 'Get-ADGroup' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-ADGroup:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : DOM1

The term 'Get-AdUser' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-AdUser:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : DOM1

The term 'Get-ADGroupMember' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-ADGroupMember:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : DOM1

The term 'Get-ADComputer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-ADComputer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : DOM1

Unable to find a default server with Active Directory Web Services running.
    + CategoryInfo          : ResourceUnavailable: (COMPANY:ADDomain) [Get-ADDomain], ADServerDownException
    + FullyQualifiedErrorId : ActiveDirectoryServer:1355,Microsoft.ActiveDirectory.Management.Commands.GetADDomain
    + PSComputerName        : DOM1

Also what's the default username & pw for the DC? The default user & ow work for the other VM's but not the DC

**Comment by jdhitsolutions** [comment]
You will see those errors until the DSC configuration converges. It may take up to 20 minutes.

**Comment by alexjriggs** [comment]
20 minute would be fine but it's sitting here for 3 days now. :(
Once the DSC configuration converges will I be able to log into the VM with the default username & password?

**Comment by jdhitsolutions** [comment]
Did you read the trouble shooting notes?

**Comment by jdhitsolutions** [comment]
Sorry for the short responses. I only had my phone handy and I am traveling overseas so my responses are off, compared to "normal".

I know this configuration works because I use it all the time on multiple computers. One thing I've seen sometime is that the Win10 VM shuts down and never restarts. I have to manually start the VM and wait for the configuration to complete. You can Ctrl+C out of the test, if you are running attended or using the Validate-Lab command. If you manually run the Pester test in the configuration folder you'll be able to see which tests are still failing.

```
invoke-pester .\vmvalidate.test.ps1
```
On rare occasions, I simply run `Wipe-Lab` and try again. This is one of the more complex configurations with a lot of moving parts.

If you still have issues, post the result of from `Get-PSAutolabSetting`.

**Comment by jdhitsolutions** [comment]
Now I'm wondering if I broke something in the test. I have this configuration installed and it seems to work just fine. Although the pester tests says nothing is configured. The lab may actually be working just fine. Looking into this further.

**Comment by jdhitsolutions** [comment]
So it does appear I need to make at least a few adjustments to the Pester test, mainly for new Windows 10 image. If you were running `Validate-Lab` or `Unattend-Lab` this means you'll never pass the tests. Although you can use the lab setup. I also have a sneaky fear that with the latest Win10 build, even though we are setting the admin password, it is getting marked as expired which is causing a problem when using that credential to remotely connect to lab members. That will take a bit more testing to verify.

**Comment by jdhitsolutions** [comment]
It would help my Pester tests if I was connecting to the correct VM!

**Comment by alexjriggs** [comment]
Tried wiping lab and starting over manually and it helped a lot. Here's my Get-PSAutolabSetting
PSVersion : 5.1.17763.771
Edition   : Desktop
OS        : Microsoft Windows 10 Enterprise LTSC
PSAutolab : 4.3.0
Lability  : 0.18.0
Pester    : 4.9.0
Memory    : 16683148

Here's what happens when I invoke the pester script manually:
Invoke-Pester .\VMValidate.test.ps1
    ____            __
   / __ \___  _____/ /____  _____
  / /_/ / _ \/ ___/ __/ _ \/ ___/
 / ____/  __(__  ) /_/  __/ /
/_/    \___/____/\__/\___/_/
Pester v4.9.0
Executing all tests in '.\VMValidate.test.ps1'

Executing script .\VMValidate.test.ps1

  Describing DOM1
    [+] [DOM1] Should belong to the COMPANY domain 408ms
    [+] [DOM1] Should have feature AD-Domain-Services installed 14ms
    [+] [DOM1] Should have feature DNS installed 2ms
    [+] [DOM1] Should have feature RSAT-AD-Tools installed 2ms
    [+] [DOM1] Should have feature RSAT-AD-PowerShell installed 2ms
    [+] [DOM1] Should have an IP address of 192.168.3.10 406ms
    [+] [DOM1] Should have a domain name of company 353ms
    [+] [DOM1] Should have organizational unit IT 10ms
    [+] [DOM1] Should have organizational unit Dev 2ms
    [+] [DOM1] Should have organizational unit Marketing 1ms
    [+] [DOM1] Should have organizational unit Sales 2ms
    [+] [DOM1] Should have organizational unit Accounting 2ms
    [+] [DOM1] Should have organizational unit JEA_Operators 2ms
    [+] [DOM1] Should have organizational unit Servers 2ms
    [+] [DOM1] Should have a group called IT 9ms
    [+] [DOM1] Should have a group called Sales 2ms
    [+] [DOM1] Should have a group called Marketing 6ms
    [+] [DOM1] Should have a group called Accounting 2ms
    [+] [DOM1] Should have a group called JEA Operators 2ms
    [+] [DOM1] Should have at least 15 user accounts 33ms
    [+] [DOM1] ArtD is a member of Domain Admins 8ms
    [+] [DOM1] AprilS is a member of Domain Admins 5ms
    [+] [DOM1] Should have a computer account for WIN10 10ms
    [+] [DOM1] Should have a computer account for SRV1 8ms
    [+] [DOM1] Should have a computer account for SRV2 8ms
    [+] [DOM1] Should have a DNS record for SRV3.COMPANY.PRI 11ms
    [+] [DOM1] Should be running Windows Server 2016 40ms

  Describing SRV1
    [+] [SRV1] Should belong to the COMPANY domain 124ms
    [+] [SRV1] Should have an IP address of 192.168.3.50 925ms
    [+] [SRV1] Should have a DNS server configuration of 192.168.3.10 8ms
    [+] [SRV1] Should be running Windows Server 2016 56ms

  Describing SRV2
    [+] [SRV2] Should belong to the COMPANY domain 129ms
    [+] [SRV2] Should have an IP address of 192.168.3.51 890ms
    [+] [SRV2] Should have a DNS server configuration of 192.168.3.10 5ms
    [+] [SRV2] Should have the Web-Server feature installed 285ms
    [+] [SRV2] Should have a sample web service file 85ms
    [+] [SRV2] Should have a WebApplication called MyWebServices 158ms
    [+] [SRV2] Should be running Windows Server 2016 26ms

  Describing SRV3
    [+] [SRV3] Should respond to WSMan requests 8ms
    [+] [SRV3] Should have an IP address of 192.168.3.60 1.14s
    [+] [SRV3] Should belong to the Workgroup domain 90ms
    [+] [SRV3] Should be running Windows Server 2019 26ms

  Describing Win10
    [+] [WIN10] Should belong to the COMPANY domain 168ms
    [+] [WIN10] Should be running Windows 10 Enterprise version 18362 32ms
    [+] [Win10] Should have an IP address of 192.168.3.100 693ms
    [+] [Win10] Should have a DNS server configuration of 192.168.3.10 3ms
    [-] [Win10] Should have RSAT installed 4.88s
      Expected regular expression 'Installed' to match 'NotPresent', but it did not match.
      221:         $pkg.State| should match "Installed"
      at <ScriptBlock>, C:\Autolab\Configurations\PowerShellLab\VMValidate.test.ps1: line 221
Tests completed in 16.48s
Tests Passed: 46, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
PS C:\Autolab\Configurations\PowerShellLab>

Seems like I'm not getting RSAT installed on the Win10 VM. I also have to keep manually starting it.

**Comment by jdhitsolutions** [comment]
Well, that at least isn't a show stopper. And you are able to manually install the RSAT packages using `Add-WindowsCapability`.  I don't want to interrupt your work but if you get a chance to set this up again and encounter the same issue try manually running:

```powershell
   Get-WindowsCapability -online -Name Rsat* | Where-Object {$_.state -ne "installed"} | Add-WindowsCapability -online
```
and report what happens.

**Comment by alexjriggs** [comment]
Sorry for the late reply. The command:
Get-WindowsCapability -online -Name Rsat* | Where-Object {$_.state -ne "installed"} | Add-WindowsCapability -online
doesn't work in the Win10 VM. None of the VM's are able to connect to the internet. I get no errors when I run enable-internet.

**Comment by jdhitsolutions** [comment]
No Internet shouldn't necessarily make a difference installing the RSAT Tools. If you run `Enable-Internet -verbose` what do you see?  @alexjriggs Is this still an open issue for you or have you moved on? I've been tied up with other work and this module got pushed to the back burner.

**Comment by alexjriggs** [comment]
Thank you. I got it going.
    On Wednesday, February 5, 2020, 08:35:09 AM PST, Jeff Hicks <notifications@github.com> wrote:  
 
 
No Internet shouldn't necessarily make a difference installing the RSAT Tools. If you run Enable-Internet -verbose what do you see? @alexjriggs Is this still an open issue for you or have you moved on? I've been tied up with other work and this module got pushed to the back burner.
