### ISSUE TITLE
Hyper-V did not installed 

### ISSUE THREAD

**Issue by waleoye** [pluralsight/PS-AutoLab-Env#206]
Hi Dale,

HyperV did not install whilst I was setting up the host so I was unable to bring up the Lab . Please can you help ?

**Comment by jdhitsolutions** [comment]
What errors did you get? What operating system are you using? Do you need to enable virtualization in your BIOS?

**Comment by waleoye** [comment]
Hi Jeff,

My machine is currently running Win 7 Enterprise 64 bits .

I will check my bios to see if I need to enable virtualization and come back to you .

Many thanks .

Regards,

Adewale



________________________________

**Comment by jdhitsolutions** [comment]
This module won't work for you.  Hyper-V on the client was introduced in Windows 8. You would need to upgrade to Windows 10 on a computer that supports virtualization.

**Comment by jdhitsolutions** [comment]
Closing this issue as there is nothing to be done.  This module won't work on Windows 7 because there is not client Hyper-V.
