### ISSUE TITLE
Lab is not loading Server with GUI

### ISSUE THREAD

**Issue by joerodr** [pluralsight/PS-AutoLab-Env#208]
Hi,

I'm trying to setup the Singleserver and Multirole Server labs for the Windows ADCS module on Pluralsight, but when the Lab install completes and I launch the DC or any server, I get a command prompts...almost as if it's server core. It allows login with the supplied password, I also checked the version (2019 Standard), but no DUI interface. What am I doing wrong? It builds the DC1, S1, N1, and CLI1 VMs in hyper-V....just no GUI....except for the CLI1 vm...that loads fine.

Am I missing something?

Thanks

Joe

**Comment by jdhitsolutions** [comment]
I don't think so. The server images are built to use Server Core so there is no GUI on the servers. Remote management should be done from the Windows 10 Client.

**Comment by joerodr** [comment]
Oh ok. I thought it was supposed to be GUI, from following the course
instructions.

Thanks for the heads up!

**Comment by jdhitsolutions** [comment]
What course are you doing? I don't think the configuration has changed much other than the images might use new versions of Windows Server. I hope that won't be an issue.

**Comment by joerodr** [comment]
I'm taking "Implementing Active Directory Certificate Services in Windows
2016 by Gary Grudzinskas". Looks like the lab now uses 2019.

**Comment by jdhitsolutions** [comment]
I'm not familiar with that course. As far as I know, this configuration always used Server Core. But, I really should maintain some backward compatibility with previous server versions. I'll also have to look at this course and see what the author is expecting.

**Comment by Pentao** [comment]
Hi all, 
I am doing the same course "Implementing Active Directory Certificate Services in Windows
2016 by Gary Grudzinskas". And facing the same issues as you Joe. 
What did you do in the end? I might just create the environment manually, unfortunately Server Core is not the best if you are trying to follow this specific course.

**Comment by joerodr** [comment]
Hi Pentao,

I ended up stepping away from the course. It looks like they now use
core.The training had a GUI for the Single Server built. Kinda tough to
follow along it the lab and training don't match. I believe the
Mult-role install is mostly core except for the Windows 10

I DO plan to return to the course. I agree, I was thinking of building it
out myself.

**Comment by jdhitsolutions** [comment]
I will need to build a new configuration that supports the old course.

**Comment by Pentao** [comment]
Hi Joe and Jeff, 
I decided to persevere with he course. What I did was to create CA1 manually, as a desktop experience server, you should be able to follow the rest of the course with the existing LAB.
For what I have seen so far, Gary manages everything from the Client VM. 

@jdhitsolutions It would be great to just have an additional configuration for a SengleServerGUI. 

Thanks for the quick responses guys, stay safe!!!

**Comment by jdhitsolutions** [comment]
I am building and testing a single server configuration using WIndows Server 2016 in desktop mode specifically for this course. Testing the build takes time but I will get it published as soon as I can.

**Comment by jdhitsolutions** [comment]
A challenge for me as a maintainer is that I have no way of knowing what configurations have been called for in Pluralsight courses. This ADCS course is a good example. The instructor is using test configurations which I assumed when I began updating were just that, for testing. So I archived them.  It isn't especially difficult to re-add a new configuration. It just takes a little time.

**Comment by jdhitsolutions** [comment]
I've pushed v4.6.0 of the module to the PowerShell Gallery. I would suggest running these commands:

```powershell
Update-Module PSAutoLab
Remove-Module PSAutoLab
Import-Module PSAutoLab
Refresh-Host
```
This should add configurations `Single-Server-GUI-2016` and `MultiRole-Server-2016`. Use the first configuration to create the standalone CA. The IP should already set to 192.168.3.75 but you'll need to rename per the course instructions.

**Comment by joerodr** [comment]
Hi Jeff,

This support is absolutely outstanding. Thanks for getting back to us and responding so quickly. I’ll try to rebuild the lab again later tonight. I’ve been really busying with the whole virus thing going on. 

Thank you both for your inputs and updates! I SO glad I posted my issue.

Please stay safe and healthy!

Thanks again 

Joe

**Comment by jdhitsolutions** [comment]
I've tweaked some of the configurations in v4.8.0 that should help with the problems that started this issue. If you update the module, be sure to run `Refresh-Host` to copy the new configuration files to your Autolab folder.

**Comment by jdhitsolutions** [comment]
I believe everything has been addressed in this issue.
