### ISSUE TITLE
Using non-evaluation ISOs

### ISSUE THREAD

**Issue by Slothy2406** [pluralsight/PS-AutoLab-Env#211]
More of a question than a issue,

Is it possible to use this to build labs with licensed products, as I would like to use some of our spare server and win10 to provide in house training, and keep the server available, just revert to clean   snapshots.

I have tried to use the full isos and reference them in the psd1 file, but I get a "Cannot Locate '<windows iso file name>' media." error.

**Comment by jdhitsolutions** [comment]
That is not what this is designed for.  I think it might be possible, but I don't know all of the changes you would have to make to get this to work with the Lability module.

**Comment by Slothy2406** [comment]
Thanks for the quick response.

Ok no problem, I will close this request down and set it off downloading the EVALs

Thanks

Andy

**Comment by jdhitsolutions** [comment]
If you can manually setup the VMs you might be able to script exporting a snapshot and then reimporting as a new VM.
