### ISSUE TITLE
password for CA1 (S1)

### ISSUE THREAD

**Issue by abs07uk** [pluralsight/PS-AutoLab-Env#212]
It doesnt match with the one given from the course

**Comment by lee-kendall** [comment]
@abs07uk I had a similar issue with the admin password, the first time I ran the set up and found that keyboard settings on the lab VM's are US English by default so if your lab host is set to English UK (like mine is), use SHIFT 2 to get the @ sign. You can obvs change the keyboard settings on all your VM's but I didn't bother!

**Comment by jdhitsolutions** [comment]
You need to tell me which course you are referring to. Although many configurations are shared among courses. If you want, you can always edit the `VMConfigurationData.psd1` file in Notepad and change the password to whatever you want.,

```powershell
  # Lab Password - assigned to Administrator and Users
   LabPassword                 = 'P@ssw0rd'
```

**Comment by abs07uk** [comment]
@lee-kendall - Thanks bro - that worked even though the password in the course and transcript is with an & and not @ - once again thanks

**Comment by abs07uk** [comment]
Thanks Jeff, the course is Implementing Active Directory Certificate Services in Windows Server 2016 - Gary Grudzinkas

The password mentioned in the lesson is P&ssw0rd and confirmed in the transcript. P@ssw0rd has worked so all good.

Thanks again.



________________________________
