### ISSUE TITLE
trying to install the lab, but unsuccessful in starting the Unattend-lab command (running windows 10 education)

### ISSUE THREAD

**Issue by wsiraj** [pluralsight/PS-AutoLab-Env#213]
[WS1] Connecting to remote server WS1 failed with the following error message : WinRM cannot process the request. The following error with errorcode
0x8009030e occurred while using Negotiate authentication: A specified logon session does not exist. It may already have been terminated.
 Possible causes are:
  -The user name or password specified are invalid.
  -Kerberos is used when no authentication method and no user name are specified.
  -Kerberos accepts domain user names, but not local user names.
  -The Service Principal Name (SPN) for the remote computer name and port does not exist.
  -The client and remote computers are in different domains and there is no trust between the two domains.
 After checking for the above issues, try the following:
  -Check the Event Viewer for events related to authentication.
  -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use HTTPS transport.
 Note that computers in the TrustedHosts list might not be authenticated.
   -For more information about WinRM configuration, run the following command: winrm help config. For more information, see the
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (WS1:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : 1312,PSSessionStateBroken

**Comment by jdhitsolutions** [comment]
It's possible your version of Windows may have limitations. What configuration are you trying to build? Also run `Get-PSAutolabSetting` and post the results. That will help determine if there are any compatibility issues.

**Comment by wsiraj** [comment]
Thanks for replying
Here is some more infor
PS C:\Autolab\Configurations\MultiRole> Get-PSAutoLabSetting


AutoLab         : C:\Autolab
PSVersion       : 5.1.18362.628
PSEdition       : Desktop
OS              : Microsoft Windows 10 Education
FreeSpaceGB     : 256.86
MemoryGB        : 16
PctFreeMemory   : 71.93
Processor       : Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
IsElevated      : True
RemotingEnabled : True
HyperV          : 10.0.18362.1
PSAutolab       : 4.8.0
Lability        : 0.19.1
Pester          : 4.10.1
PowerShellGet   : 1.0.0.1

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wsiraj** [comment]
Trying to built  “MultiRole” environment

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jdhitsolutions** [comment]
Is WS1 your computer? Did Setup-Host run without any errors?

**Comment by wsiraj** [comment]
Yes ws1 is my laptop and yes setup-host run without any error

Sent from my iPhone

On Apr 21, 2020, at 6:36 PM, Jeff Hicks <notifications@github.com> wrote:

﻿

Is WS1 your computer? Did Setup-Host run without any errors?

**Comment by jdhitsolutions** [comment]
Take a look at the manual configuration steps in https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Detailed-Setup-Instructions.md and try them on your system.  

Is your computer managed at all by any Group Policies or locked down in any way?

**Comment by jdhitsolutions** [comment]
Also, what result do you get from this command:

```powershell
Get-Item -Path WSMan:\localhost\Client\TrustedHosts
```

**Comment by lee-kendall** [comment]
Hi, i'm also experiencing similar lab build issues yesterday after i completely wiped my older 4.7.0 and upgraded to 4.8.0. I tried installing SingleServer-GUI-2016 & MultiRole-Server-2016. Both failed and generated xx.mof.error files in their respective config directory for eached failed VM. I did manage to install Windows10 and currently installing SingleServer this morning...so far ok. I will try the others again later today

**Comment by jdhitsolutions** [comment]
Same errors or different?

**Comment by jdhitsolutions** [comment]
It is important to remember that if you are seeing errors during validation, that is perfectly normal until the configuration merges. That might take anywhere from 10-60 minutes depending on the configuration.

**Comment by wsiraj** [comment]
I have successfully install the AutoLab environment with the manual process. Still testing , looks good so far

PS C:\Autolab\Configurations\MultiRole> Get-Item -Path WSMan:\localhost\Client\TrustedHosts


   WSManConfig: Microsoft.WSMan.Management\WSMan::localhost\Client

Type            Name                           SourceOfValue   Value
----            ----                           -------------   -----
System.String   TrustedHosts                                   <local>

Thanks for your help

Wasim


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lee-kendall** [comment]
initally i was seeing the same error as reported above so i trashed my whole lab and upgraded Autolab. Then i tried to run the setup-lab cmds for SingleServer-GUI-2016 & MultiRole-Server-2016 and it appears to start ok and then freaks out just after the "build the .mof files from configurations" - I click {R} for run once and then see erros in the screenshot
![mof_erros](https://user-images.githubusercontent.com/62287276/80005212-2acc3c00-84bb-11ea-9029-9140c6bc838e.JPG)

There is a xx.mof.error file within the respective config folder for each lab. I though it was just my host until i read this new post so perhaps it could be a genuine problem?

**Comment by jdhitsolutions** [comment]
If you had a previous version of the module installed and then updated the module to v4.8.0, be sure to run `Refresh-Host` which will update the configuration data.  I'd run `Wipe-Lab` again. run `Refresh-Host` and try again.

**Comment by jdhitsolutions** [comment]
@lee-kendall   I looked closer at the error message and I've seen that with out of date DSC resources. I would suggest running these steps:

```powershell
Wipe-Lab
Update-Module PSAutolab -force
remove-module PSAutolab
import-module  PSAutolab
refresh-host
```
Then try the lab again.

**Comment by lee-kendall** [comment]
Thanks @jdhitsolutions 
Will try that

**Comment by DerakW** [comment]
I had this same issue.  Seems to have something to do with me using a O365 account to log into my computer.   To fix it , I created a local user and added it to the administrators group.  Then logged into my computer with that user and everything ran as expected.

**Comment by jdhitsolutions** [comment]
That is a useful bit of information. I never considered people would not be using local accounts.

**Comment by jdhitsolutions** [comment]
I think everything has been addressed in this issue. I've added some comments to the README about using a local account.
