### ISSUE TITLE
Wrong Windows Enterprise Version in the VM Validation

### ISSUE THREAD

**Issue by magichappens89** [pluralsight/PS-AutoLab-Env#214]
Hello,
for me it looks like there is a new build version which needs to be changed in the validation script but maybe I did something wrong?
I ran into an error when running "Validate-Lab" for the PowerShellLab. "Invoke-Pester .\VMValidate.test.ps1" showed me that version "Should Be '10.0.18362'" but is '10.0.18363", so I changed it in the script. Not sure if that should be changed in the master files as well.
Kind regards,
Mario

**Comment by jdhitsolutions** [comment]
I wonder if the new version of Lability is pulling down a newer Windows 10 ISO.  This test result doesn't really affect the lab setup so it can probably be removed.

**Comment by jdhitsolutions** [comment]
It does indeed look like there is a new ISO file with a different version number. Since I re-use Autolab all the time, I was still using the previous ISO file. I've removed testing for the version number since it is really irrelevant. It will be released with v4.8.1.

**Comment by magichappens89** [comment]
Great! Thanks for that. I will proceed with your Pluralsight course then :)

**Comment by jdhitsolutions** [comment]
I got it. Thanks for the catch.
