### ISSUE TITLE
2012R2 labs and ISO spanish language

### ISSUE THREAD

**Issue by mgonzcast** [pluralsight/PS-AutoLab-Env#215]
First of all, thanks for creating this amazing tool.

I have to test a migration from 2012R2 to 2016 so I need to build a 2012R2 lab. I see that it was listed in the ISO list but even in archive I don´t see any 2012R2 lab. Is there any?

Also I was wondering if I have to take into account anything in particular to create my own labs based on existing ones but using Spanish ISOs.

Thanks!

**Comment by jdhitsolutions** [comment]
You could modify an existing configuration but it might be easier if I do it for you as I am in the midst of updating configurations. I could create a single 2012R2 server configuration. I'm not sure about the Spanish requirement. I'd have to see if that is a download option.

**Comment by jdhitsolutions** [comment]
I added 2 Windows Server 2012 RS configurations in v4.9.0 which has been published to the PowerShell Gallery. Still looking into non-English images.

**Comment by mgonzcast** [comment]
I run update-module psautolab and now I have two psautolab modules (version 4.8.0 and 4.9.0).

I don´t see those 2 Windows Server 2012R2 configurations.

**Comment by jdhitsolutions** [comment]
After you update the module run `Refresh-Host` which will copy the updated configurations to your Autolab folder.

**Comment by mgonzcast** [comment]
That worked. Thanks! Let me know if I can help about the Spanish ISO thing

**Comment by mgonzcast** [comment]
> I added 2 Windows Server 2012 RS configurations in v4.9.0 which has been published to the PowerShell Gallery. Still looking into non-English images.

Why does it ask me to have automatedlab module installed?

```
PS C:\WINDOWS\system32> install-module psautolab
ADVERTENCIA: Unable to resolve package source 'C:\Program Files\WindowsPowerShell\Modules\AutomatedLab\5.17.0\'.
```

**Comment by jdhitsolutions** [comment]
I don't know what that is or why it would show up. That is very strange PowerShell behavior.

If you had previously installed this module you should be able to run `Update-Module PSAutolab -force`. The other option, assuming you never installed this module is to try this: `Find-Module psautolab | Install-module -force`.

**Comment by mgonzcast** [comment]
Thanks! It seems a cosmetic issue. Anyway, as you can see in the lability github forum I managed to install the 2012R2-GUI lab in Spanish. Is there any lab for a DC, CA and Exchange for 2012R2 that you can upload or any guidance of tweaking any existing one for a newer Windows Server version?

**Comment by jdhitsolutions** [comment]
There is nothing for 2012R2 other than the single server configurations I created. You will need to setup your own environment. You can manually create additional virtual machines using the ISO files to install from. Once you have everything setup, be sure to checkpoint everything. You might even want to export or backup all of the VM so you can restore them later. Just know that there is a time limit on the evaluation ISOs.

**Comment by mgonzcast** [comment]
> There is nothing for 2012R2 other than the single server configurations I created. You will need to setup your own environment. You can manually create additional virtual machines using the ISO files to install from. Once you have everything setup, be sure to checkpoint everything. You might even want to export or backup all of the VM so you can restore them later. Just know that there is a time limit on the evaluation ISOs.

Any guidance or help you can provide for creating my own labs? Maybe I could use as a base any of the existing ones? Or things change a lot from 2012R2 to 2016? I don´t see any lab that deploys a CA

**Comment by jdhitsolutions** [comment]
The PowerShellLab includes an Active Directory CA. although the configuration probably needs a few more manual steps. Unless you have solid DSC experience, your best bet is to manually install and configure what you need then checkpoint the VMs.  Again, what you are trying to do and your use case is beyond the scope of this module.

**Comment by jdhitsolutions** [comment]
Closing this because the original issue has been resolved.
