### ISSUE TITLE
Update PowerShellGet module in PowerShellLab

### ISSUE THREAD

**Issue by jdhitsolutions** [pluralsight/PS-AutoLab-Env#216]
It looks like the PowerShellGet module in the PowerShellLab VMs needs to be updated. Without the newer versions I think some PowerShell commands will fail.

**Comment by jdhitsolutions** [comment]
DOM1 at least might need to have TLS configured

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

**Comment by lee-kendall** [comment]
> DOM1 at least might need to have TLS configured
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Thanks for this, I had issues today trying to install the MSonline module as part of the ADFS training lab. Enabling TLS1.2 on my 2016 server solved the problem

**Comment by jdhitsolutions** [comment]
I found the registry settings that I think I can make during setup that should take care of this.

**Comment by jdhitsolutions** [comment]
All configurations will have registry settings to configure this TLS setting in v4.10.0
