### ISSUE TITLE
Update-Lab doesn't work if EnvironmentPrefix was used

### ISSUE THREAD

**Issue by michulo** [pluralsight/PS-AutoLab-Env#217]
After creating lab with "EnvironmentPrefix" set in VMConfigurationData.psd1 command
` update-lab`  tries update VM based on NodeName without EnvironmentPrefix and  returns:

```
Get-VM : Hyper-V was unable to find a virtual machine with name "DC1".
At C:\Program Files\WindowsPowerShell\Modules\PSAutoLab\4.9.0\functions\public.ps1:1230 char:23
+                 $vm = Get-VM -name $node.Nodename
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (DC1:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

```

```
AutoLab         : C:\_mo\VMs\AutoLab
PSVersion       : 5.1.17763.1007
PSEdition       : Desktop
OS              : Microsoft Windows 10 Pro
FreeSpaceGB     : 69,59
MemoryGB        : 16
PctFreeMemory   : 61,79
Processor       : Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
IsElevated      : True
RemotingEnabled : True
HyperV          : 10.0.17763.1
PSAutolab       : {4.9.0, 4.8.0, 4.3.0}
Lability        : {0.19.1, 0.18.0, 0.10.1}
Pester          : 4.9.0
PowerShellGet   : 1.0.0.1
```

**Comment by jdhitsolutions** [comment]
Even though that comment is in the psd1 file, I don't think it has ever been used or tested. I'll have to look into this.

**Comment by jdhitsolutions** [comment]
I know that if you use a prefix, the validation tests will never work And I'm trying to figure out how I could make that possible.

**Comment by jdhitsolutions** [comment]
`Update-Lab` isn't expecting a prefix. Not that I couldn't make it work. In all the years I've been working with this module, this is the first time anyone has used the prefix option. I have to decide if that feature can be allowed. The biggest issue is the validation tests.

Why did you decide to use the environment prefix?

**Comment by jdhitsolutions** [comment]
I have made what should be the necessary updates. Update to v4.10.0 of the module. Be sure to run `Refresh-Host` to update configuration files. You still have to manually edit `VmConfigurationData.psd1` to enable the environment prefix.

**Comment by michulo** [comment]
> Why did you decide to use the environment prefix?

I'm using it for distinguishing laboratories based on this same configuration. I just create copy of configuration and without environment prfix I have to change name of each node. With environment prefix VM name differs it is easier to manage VM in Hyper-V.

**Comment by jdhitsolutions** [comment]
Are you trying to have 2 copies of the same configuration running at once?

**Comment by michulo** [comment]
Generally I run one at time but I've got many configured,
I think that running many is also possible but it requires more modifications of config files (names, IP addresses), correct me if I'm wrong.

**Comment by jdhitsolutions** [comment]
The module was designed with the assumption users were running a single lab at a time for a given Pluralsight course. You can set up as many configurations at once as you want. Using the prefix would be a good way to keep the VMs straight and that should now work. You have to be aware of VMs in configurations that might use the same IP address. That's where the `Get-LabSummary` command comes in handy.  But otherwise, you are correct in that you would need to edit the configuration data. I'd suggest copying the entire folder with a new name and edit the copy.

And now with v4.10.0 commands will now work with an environment prefix. Is there anything else with this particular issue that needs to be addressed?

**Comment by michulo** [comment]
no thank you
