### ISSUE TITLE
errorcode 0x8009030e

### ISSUE THREAD

**Issue by StormPrince** [pluralsight/PS-AutoLab-Env#219]
HI, I'm a newtorking student trying to install the PS AutoLab but this errorcode is in my way. Can you advise me on how to continue? I have attached a screenshot of the error message and the PSAutoLabSetting result below:-
![Annotation 2020-05-14 124158](https://user-images.githubusercontent.com/65329442/81897219-6650b680-95e0-11ea-8130-7e17497680a7.png)

**Comment by jdhitsolutions** [comment]
You need to be in the configuration folder for the lab you want to create.

```powershell
PS C:\Autolab\Configurations\PowerShellLab> unattend-lab
```

**Comment by StormPrince** [comment]
Thanks, but it made no difference. Same error message.
Perhaps something with PS remoting permissions?

**Comment by jdhitsolutions** [comment]
This doesn't make sense. Is your computer managed at all by Group Policy?  I would suggest you look at https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Detailed-Setup-Instructions.md and then try running the manual setup. Run commands with -Verbose and let's see what is happening just before the error occurs.

**Comment by jdhitsolutions** [comment]
I'm assuming when you ran `Setup-Host` everything ran without error?

**Comment by jdhitsolutions** [comment]
Is this still an issue?

**Comment by StormPrince** [comment]
Tried everything suggested here and by others. Gave up. Downloaded VMware
Workstation. No more problems. I have a functioning virtual lab with no
hassles at all.
Thanks for your help anyway.
