### ISSUE TITLE
Run-Lab command producing error

### ISSUE THREAD

**Issue by CannaBaroness** [pluralsight/PS-AutoLab-Env#220]
Hi, I've been trying to install PSAutoLab for the past three days, and now I can't seem to get past this error message.  Could you please advise on how to proceed?
Thanks!

<img width="782" alt="Screen Shot 2020-05-14 at 5 30 21 PM" src="https://user-images.githubusercontent.com/41597074/81993354-1a673700-960b-11ea-91e6-c1c6748294ee.png">

**Comment by michulo** [comment]
Are you able to run VM from Hyper-v manager?
Is there a chance you have Virtual Box or other Hypervisor installed on that machine?

**Comment by jdhitsolutions** [comment]
I don't know how I missed the notification for this issue. My apologies. Were you able to eventually get this working or is this still an open issue?

**Comment by jdhitsolutions** [comment]
Closing for now as an abandoned issue. If this is still something to look at we can easily re-open it.
