### ISSUE TITLE
I'm Prompted for Output File

### ISSUE THREAD

**Issue by cubsa** [pluralsight/PS-AutoLab-Env#222]
Hello:

I'm working on the AutoLab.  I was able to run the script to create the lab and download the ISOs.  However, when I run Validate-lab, I get the message, "Supply Values for the following parameters: OuputFile:"
I run Validate-Lab from both the configurations folder and the multirole folder.  Sorry but I'm not to good with PowerShell.  Please assist. 

Thanks,

Cubsa

![image](https://user-images.githubusercontent.com/66501013/83932337-cfef5b00-a76f-11ea-9783-411eee621cde.png)
![Validate_Lab](https://user-images.githubusercontent.com/66501013/83932350-db428680-a76f-11ea-9e11-d78722d3165a.png)

**Comment by jdhitsolutions** [comment]
You have to be in a configuration folder to run any of the commands. Take a look at the detailed instructions. https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Detailed-Setup-Instructions.md

**Comment by cubsa** [comment]
Hello Jeff:
Thank you very much for your prompt reply.  I did try it in the configurations folder.  Please see attached.  In the meantime, I'll review the page.  
Best Regards, 
Sergio 

    On Saturday, June 6, 2020, 09:49:00 AM EDT, Jeff Hicks <notifications@github.com> wrote:  
 
 


You have to be in a configuration folder to run any of the commands. Take a look at the detailed instructions. https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Detailed-Setup-Instructions.md

**Comment by jdhitsolutions** [comment]
Is this still an open issue?

**Comment by cubsa** [comment]
Jeff:
It is but I'm able to run the lab, so go ahead and close the ticket.

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 16, 2020 at 9:44 AM, Jeff Hicks<notifications@github.com> wrote:   


Is this still an open issue?
