### ISSUE TITLE
Unable to download NuGet

### ISSUE THREAD

**Issue by Markor360** [pluralsight/PS-AutoLab-Env#224]
I'm unable to download and install NuGet. I run the Install-Module -Force SkipPublisherCheck command and get the follow error.
[No NuGet install.txt](https://github.com/pluralsight/PS-AutoLab-Env/files/4766498/No.NuGet.install.txt)

**Comment by jdhitsolutions** [comment]
What version of Windows and PowerShell are you running? 

if you run `Find-PackageProvider` do you see nuget listed? If so try this:

```powershell
Install-packageprovider -name nuget -requiredversion 2.8.5.201 -force -forcebootstrap
```

**Comment by andreasjordan** [comment]
You had this error:

    WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.

Depending on the windows-version, old TLS version is used and not allowed by the server at microsoft.
Try this to use only new TLS versions:

    Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value 1

I normaly use this to set up PowerShell on new maschines:

    Install-PackageProvider -Name Nuget -Force | Out-Null
    Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

**Comment by jdhitsolutions** [comment]
Is this still an open issue?

**Comment by jdhitsolutions** [comment]
I put this line in my PowerShell profile.

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

**Comment by jdhitsolutions** [comment]
I'm wondering if I should just make this part of the module.

**Comment by Markor360** [comment]
Thanks for response, but I’m not currently working on this course anymore. I’ve moved onto something else.
