### ISSUE TITLE
Error Downloading 2019_x64_Standard_Core_EN_Eval Media (also Datacenter)

### ISSUE THREAD

**Issue by thepaulmacca** [pluralsight/PS-AutoLab-Env#225]
I just want to check here if anyone else is having this issue. The 2019_x64_Standard_EN_Eval media downloads fine, which is weird as I'm assuming it's the same ISO?

**Comment by jdhitsolutions** [comment]
What error are you seeing? What configuration are you trying to use?

**Comment by jdhitsolutions** [comment]
I think I see now. I deleted the 2019 ISO and trying building the SingleServer ISO. Nothing downloaded. MS probably changed the download link. I'll have to see what needs to be updated.

**Comment by thepaulmacca** [comment]
Yep think that’s it as I’m seeing a different link to what’s in the Lability config. I’ll do a Lability PR to update the links if you like?

________________________________

**Comment by jdhitsolutions** [comment]
I can manually download the ISO using the media link in my browser. So the link must be fine.

**Comment by jdhitsolutions** [comment]
Odd. I tried building another lab that would require downloading an ISO and I get the same result. Nothing has changed in the code that would account for that.

**Comment by thepaulmacca** [comment]
That’s weird as I tried manually downloading the ISO last night and I had a different link to what’s in the config

I think that’s part of the problem with this tho, the links keep changing all the time!

**Comment by jdhitsolutions** [comment]
The links in the module are static. 

```text
PS D:\Autolab\Configurations\SingleServer2012R2> Get-Labmedia -id 2019_x64_Standard_EN_Eval | format-list


Id              : 2019_x64_Standard_EN_Eval
Filename        : 2019_x64_EN_Eval.iso
Description     : Windows Server 2019 Standard 64bit English Evaluation with Desktop Experience
Architecture    : x64
ImageName       : 2
MediaType       : ISO
OperatingSystem : Windows
Uri             : https://software-download.microsoft.com/download/sg/17763.253.190108-0006.rs5_release_svc_refres
                  h_SERVER_EVAL_x64FRE_en-us.iso
Checksum        : 48CD91270581D1BE10C3FF3AD6C41CCE
CustomData      : @{WindowsOptionalFeature=System.Object[]; MinimumDismVersion=10.0.0.0}
Hotfixes        : {}
```

I pasted this URI into my browser and downloaded the ISO. And it doesn't look like it changed in the browser.

**Comment by thepaulmacca** [comment]
Weird, I’m in the UK and I get a different link to that one. Like I said I think that’s part of the problem with the links changing at times

For now I’ll prob go download the ISO manually and use custom media

________________________________

**Comment by jdhitsolutions** [comment]
Do you have a 2019 disk file in Autolab\MasterVirtualDisks ? If so, the ISO won't be downloaded as Autolab already has what it needs.

**Comment by jdhitsolutions** [comment]
That's likely the case. I deleted the 2019 VHDX files, re-ran setup and now it is downloading.

**Comment by thepaulmacca** [comment]
I don’t have any VHDX files yet, this is a new setup. I’ll try again tonight and see how that goes!

**Comment by jdhitsolutions** [comment]
That's very odd then. Run `Get-PSAutolabSetting` and post the results.

**Comment by thepaulmacca** [comment]
Will do Jeff

Thanks for your help and for the work you’re putting into the module, appreciate it

________________________________

**Comment by thepaulmacca** [comment]
Right so I've tried again tonight and I'm getting an error still:

![Annotation 2020-06-15 212736](https://user-images.githubusercontent.com/41340540/84703525-4bab8d80-af50-11ea-934c-c4042faf7183.png)

This is what I see when I run Get-PSAutolabSetting:

![Annotation 2020-06-15 213150](https://user-images.githubusercontent.com/41340540/84703576-67169880-af50-11ea-9446-440d7119338e.png)

If I run `Get-LabMedia -Id 2019_x64_Standard_Core_EN_Eval | Format-List`, nothing is returned. The same goes for if I run the command for Datacenter

The issue is definitely to do with the Core images

**Comment by jdhitsolutions** [comment]
You modified a lab. Post the changes you made.

**Comment by thepaulmacca** [comment]
I created a new lab using the PowerShellLab configuration (I used it as a template to build from as I've had previous experience with Autolab a few years ago)

If I run `Invoke-LabResourceDownload -MediaId 2019_x64_Standard_Core_EN_Eval`, I get this error:

![Annotation 2020-06-15 231435](https://user-images.githubusercontent.com/41340540/84711340-ff674a00-af5d-11ea-869c-70bf2a9c91d0.png)

The same error occurs with Datacenter_Core

If I run `Invoke-LabResourceDownload -MediaId 2019_x64_Standard_EN_Eval`, that downloads fine

Do you notice that aswell?

**Comment by jdhitsolutions** [comment]
That's not the way that Lability command is designed.  If your configuration file is correct, you shouldn't have to do anything other than run Setup-Lab.

As for `Get-LabMedia` I think you are simply turning the name around:

```text
PS D:\> Get-LabMedia -Id 2019_x64_Standard_EN_Core_Eval

Id                             Arch Media Description
--                             ---- ----- -----------
2019_x64_Standard_EN_Core_Eval  x64   ISO Windows Server 2019 Standard 64bit English Evaluation
```

**Comment by thepaulmacca** [comment]
Right, but the MOF files have been created, so know the configuration is good

Do you see the same issue if you run that command for Standard & Core ISOs? (downloads for Standard but not Core)

________________________________

**Comment by jdhitsolutions** [comment]
If the problem is that your configuration isn't downloading what you think it should, you need to post your configuration so I can look at and and test it.  The problem isn't the MOF files but the non-node data that Lability needs which is in the psd1 file. I don't doubt the MOFs are fine. It's the rest of the configuration we need to look at.

**Comment by thepaulmacca** [comment]
Ok well I’ll try again tonight without the Core ISO, and if it still fails then I’ll post the config I’m using (my config is using both Standard and Core ISOs at present)

________________________________

**Comment by jdhitsolutions** [comment]
I'm suspecting you have the equivalent of a typo that sometimes you just need another set of eyes to see it.

**Comment by thepaulmacca** [comment]
Yep probably, sorry to have wasted your time if that’s the case! I’ll give you an update later today

________________________________

**Comment by jdhitsolutions** [comment]
It's not a waste. I'm happy to help. You are doing something custom which is rarely done. If I can learn what obstacles you are encountering, I can at least write better help documentation.

**Comment by thepaulmacca** [comment]
Right Jeff I'm going to hold my hands up and apologise for wasting your time, it was a typo...

Instead of `2019_x64_Standard_EN_Core_Eval`, I had `2019_x64_Standard_Core_EN_Eval` in my config. Now that I've rectified it, it's downloading and building fine

That'll teach me for doing these things late at night, and not double-checking with 'Get-LabMedia' first for the correct name 😐
