### ISSUE TITLE
Configurations\PowerShellLab\VMValidate.test.ps1 - "Should Be $True" is missing

### ISSUE THREAD

**Issue by andreasjordan** [pluralsight/PS-AutoLab-Env#226]
The tests for ArtD and AprilS as members of Domain Admins always succeeds, because "Should Be $True" is missing at the end of line 116 and 120.

**Comment by jdhitsolutions** [comment]
That actually isn't required. In a Pester test, all you need is code in the IT block that can be True or False.  This code: `$admins.name -contains 'artd'` already does that so there's no need to pipe it to Should.

**Comment by jdhitsolutions** [comment]
But...now that I test it this doesn't seem to be the case.

**Comment by jdhitsolutions** [comment]
Huh. I could swear I've written other tests that handle their own validation. But this is an easy fix.

**Comment by jdhitsolutions** [comment]
I fixed the tests in v4.13.0. Run `Update-Module PSAutolab` and then run `Refresh-Host`.
