### ISSUE TITLE
UseLocalTimeZone in Invoke-SetupLab doesn't work on german system

### ISSUE THREAD

**Issue by andreasjordan** [pluralsight/PS-AutoLab-Env#227]
UseLocalTimeZone in Invoke-SetupLab uses "[System.TimeZone]::CurrentTimeZone.StandardName" to get the local time zone. This returns "Mitteleuropäische Zeit" on a german system. For the functionality to work correctly, the term "W. Europe Standard Time" is needed, as returned by "(Get-TimeZone).Id". But I don't now if this has negative effects on english systems.

**Comment by jdhitsolutions** [comment]
Thanks for reporting this. This is one of those things that is hard to test for. But I think Get-TimeZone will work.  This will be added in v4.13.0

**Comment by jdhitsolutions** [comment]
v4.13.0 has been published to the PSGallery. Run `Update-Module`  then run `Refresh-Host`. Let me know if this fixes the problem.

**Comment by andreasjordan** [comment]
Yes, works perfect. Thank you very much.
