### ISSUE TITLE
[New Feature] Wipe-Lab should just switch of the VMs instead of shutting them down gracefully

### ISSUE THREAD

**Issue by andreasjordan** [pluralsight/PS-AutoLab-Env#229]
When I wipe the lab, I don't care about the VMs, So instead of shutting them down gracefully and in the right order, it would be faster to get all the VM names from the config and shut when down with "Stop-VM -TurnOff".

**Comment by jdhitsolutions** [comment]
That makes sense to me and seems like a reasonable enhancement.

**Comment by andreasjordan** [comment]
I can try to write the code for that, if you wish.

**Comment by jdhitsolutions** [comment]
I'll take care of it. I have a few other items for the next release. In the mean-time you can run `stop-vm -VMName (Get-Labsummary).computername` and then `Wipe-Lab`

**Comment by jdhitsolutions** [comment]
This will be included in v4.15.0 when it is released.

**Comment by jdhitsolutions** [comment]
This has been added in v4.15.0.

```powershell
Update-Module PSAutolab -force
Refresh-Host
```
Definitely wipes labs faster. Thanks for the suggestion.
