### ISSUE TITLE
Why is Invoke-WUUpdate in private.ps1 and public.ps1?

### ISSUE THREAD

**Issue by andreasjordan** [pluralsight/PS-AutoLab-Env#230]
I found the commandlet Invoke-WUUpdate in both private.ps1 and public.ps1. Is there a reason for that?

**Comment by jdhitsolutions** [comment]
At one point some of that code started as private. I must have copied to public and never cleaned up. I will have to look. Thanks for catching that.

**Comment by jdhitsolutions** [comment]
I reviewed the code and cleaned up the mess. Changes will be in v4.15.0. As way of background, the function originally started as a public function but then I created `Update-Lab` which was intended to call the function as a private function. I neglected to clean up the code.

**Comment by jdhitsolutions** [comment]
v4.15.0 has been published which corrects this.
