### ISSUE TITLE
Wipe-Lab not working when using EnvironmentPrefix

### ISSUE THREAD

**Issue by andreasjordan** [pluralsight/PS-AutoLab-Env#231]
Wipe-Lab uses `Hyper-V\Stop-VM -vmname (PSAutolab\Get-LabSummary -Path $Path).Computername -TurnOff` to turn off the VMs. But when using EnvironmentPrefix, then Computername is not the name of the VM.

**Comment by andreasjordan** [comment]
I changed "Get-LabSummary" a bit to include VMName:

```
            Write-Verbose "Getting node data from $psd1"
            $Nodes = (Import-PowerShellDataFile -Path $psd1).allNodes

            Write-Verbose "Getting environment prefix data from $psd1"
            $EnvironmentPrefix = (Import-PowerShellDataFile -Path $psd1).NonNodeData.Lability.EnvironmentPrefix

            $nodes.where( {$_.Nodename -ne '*'}).Foreach( {
                    if ($_.lability_startupmemory) {
                        $mem = $_.lability_startupmemory
                    }
                    elseif ($_.lability_MinimumMemory) {
                        $mem = $_.lability_minimummemory
                    }
                    else {
                        $mem = $nodes[0].Lability_MinimumMemory
                    }
                    if ($_.Lability_ProcessorCount) {
                        $ProcCount = $_.Lability_ProcessorCount
                    }
                    else {
                        $ProcCount = 1
                    }
                    [pscustomobject]@{
                        PSTypeName   = "PSAutolabVM"
                        Computername = $_.NodeName
                        VMName       = $EnvironmentPrefix + $_.NodeName
                        InstallMedia = $_.lability_media
                        Description  = $media[$_.lability_media]
                        Role         = $_.Role
                        IPAddress    = $_.IPAddress
                        MemoryGB     = $mem / 1GB
                        Processors   = $ProcCount
                        Lab          = $labname
                    }
                })

```

And I changed "Wipe-Lab" to use this: 
```
Hyper-V\Stop-VM -vmname (PSAutolab\Get-LabSummary -Path $Path).VMName -TurnOff
```

That works on my maschine.

**Comment by jdhitsolutions** [comment]
I thought I had this handled. Guess I'll take a second look.

**Comment by jdhitsolutions** [comment]
I finally have some time to look at this. Now I see what you are trying to do. The Get-LabSummary is designed to use the default configuration to show the user what VMs will be created.  This command was intended for someone to use for planning or discovery purposes. The prefix is irrelevant in this regard.  BUT...I can see where this is now a potential issue. I have a slightly different fix in mind which is (hopefully) less intrusive. Working on it now.

**Comment by jdhitsolutions** [comment]
Update to v4.16.0 of the module and try the commands again. The new version includes the prefix in the computer name if it is defined.

**Comment by andreasjordan** [comment]
Ok, thanks. So "Computername" is the name of the VM, but not the name of the installed operating system in that VM anymore. And the "Computername" is not the name of the node in the VMConfigurationData.psd1 anymore.
This might be totally ok, just wanted to note this.
I can test this maybe tomorrow.

**Comment by jdhitsolutions** [comment]
The computer name never reflected the operating system, except when we used Nano images. Although there might be an odd exception I'm forgetting. The module was originally designed for users with little to no PowerShell experience, or even that they might be IT Pros. To keep things simple the VM name and computer name in the lab were kept the same. The idea was to use the module commands to manage everything. More experienced users can jump in and use the Hyper-V cmdlets, but that was never the intention of this module.  We didn't even expect many people to use the prefix setting. The changes I've made should make it easier to detect the computer name when a prefix is used.

**Comment by jdhitsolutions** [comment]
On second thought, I still may not have this quite right.

**Comment by jdhitsolutions** [comment]
I updated `Get-LabSummary` again which is essentially what you originally suggested. :smile:   Update to v4.17.0 and try again.

**Comment by andreasjordan** [comment]
Just run a test: Works!
Thanks for the change.
