### ISSUE TITLE
RSAT problem+solution on W10 PS C:\Autolab\Configurations\Jason-DSC-Env> Invoke-Pester .\vmvalidate.test.ps1

### ISSUE THREAD

**Issue by roman-peltzer-ict-solutions** [pluralsight/PS-AutoLab-Env#232]
Works great this Auto-Lab

**Comment by MennoDeRuiter-IctSolutions** [comment]
The latest W10 changed the way RSAT can be installed with PowerShell

So, Jason's lab doesn't work (at least, on the CLI1 

PS C:\Autolab\Configurations\Jason-DSC-Env> Invoke-Pester .\vmvalidate.test.ps1

Here is described the new way RSAT is installed..
https://www.prajwaldesai.com/install-rsat-tools-on-windows-10-version-1809/#:~:text=Instead%2C%20on%20your%20Windows%2010,specific%20RSAT%20tools%20you%20need.

these are the errors:

  Describing Cli1
    [+] [CLI] Should accept domain admin credential 1ms
    [+] [CLI1] Should have an IP address of 192.168.3.100 1.1s
    [-] [CLI1] Should have RSAT installed 5.26s
      Expected $null, but got @(Microsoft.Dism.Commands.AdvancedCapabilityObject, Microsoft.Dism.Commands.AdvancedCapabilityObject, Microsoft.Dism.Commands.AdvancedCapabilityObject, Microsoft.Dism.Commands.AdvancedCapabilityObject, Microsoft.Dism.Commands.AdvancedCapabilityObject, Microsoft.Dism.Commands.AdvancedCapabilityObject, Microsoft.Dism.Commands.AdvancedCapabilityObject, Microsoft.Dism.Commands.AdvancedCapabilityObject, Microsoft.Dism.Commands.AdvancedCapabilityObject, Microsoft.Dism.Commands.AdvancedCapabilityObject).
      236:             $pkg | Where-Object { $_.state -ne "installed"} | Should be $Null
      at <ScriptBlock>, C:\Autolab\Configurations\Jason-DSC-Env\VMValidate.test.ps1: line 236
    [+] [CLI1] Should have a DNS server configuration of 192.168.3.10 1ms
Tests completed in 13.45s
Tests Passed: 35, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
PS C:\Autolab\Configurations\Jason-DSC-Env>
