### ISSUE TITLE
LabNat not found

### ISSUE THREAD

**Issue by fjavaler** [pluralsight/PS-AutoLab-Env#234]
_AutoLab                     : C:\Lability
PSVersion                   : 5.1.19041.1
PSEdition                   : Desktop
OS                          : Microsoft Windows 10 Pro
FreeSpaceGB                 : 124.89
MemoryGB                    : 16
PctFreeMemory               : 56.77
Processor                   : Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
IsElevated                  : True
RemotingEnabled             : False
HyperV                      : 10.0.19041.1
PSAutolab                   : 4.15.0
Lability                    : 0.19.1
Pester                      : {4.10.1, 3.4.0}
PowerShellGet               : 1.0.0.1
PSDesiredStateConfiguration : 1.1_

Hi, when I run `Get-NetNat LabNat` I get the following error:

```
Get-NetNat : No MSFT_NetNat objects found with property 'Name' equal to 'LabNat'.  Verify the value of the property and retry.
At line:1 char:1
+ Get-NetNat LabNat
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (LabNat:String) [Get-NetNat], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_Name,Get-NetNat
```

**Comment by jdhitsolutions** [comment]
Did you run a lab setup? If I recall correctly, the NAT isn't setup until you do.

**Comment by fjavaler** [comment]
Following the Readme, I have executed the :
`
PS C:\> Install-Module PSAutoLab -Force -SkipPublisherCheck `

command, and the:

```
PS C:\> Import-Module PSAutolab -force
PS C:\> Get-Module PSAutolab
```
commands.

**Comment by jdhitsolutions** [comment]
You need to run Setup-Host and then set up a lab. Take a look at https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Detailed-Setup-Instructions.md

**Comment by fjavaler** [comment]
Okay, sounds good. Thank you!
