### ISSUE TITLE
HyperVisor Components Missing 

### ISSUE THREAD

**Issue by bankershours** [pluralsight/PS-AutoLab-Env#236]
`❯ Get-PSAutoLabSetting

AutoLab                     : C:\Autolab
PSVersion                   : 5.1.19041.1
PSEdition                   : Desktop
OS                          : Microsoft Windows 10 Pro
FreeSpaceGB                 : 82.3
MemoryGB                    : 7
PctFreeMemory               : 57.02
Processor                   : Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
IsElevated                  : True
RemotingEnabled             : True
HyperV                      : 10.0.19041.1
PSAutolab                   : 4.17.0
Lability                    : 0.19.1
Pester                      : {4.10.1, 3.4.0}
PowerShellGet               : 1.0.0.1
PSDesiredStateConfiguration : 1.1

⚡ nickmoore@nickmoore003  C:\Autolab\Configurations\Windows10                                               [19:55]
❯ get-ciminstance win32_operatingsystem | Select-Object Caption,Version,Buildnumber,TotalVisibleMemorySize

Caption                  Version    Buildnumber TotalVisibleMemorySize
-------                  -------    ----------- ----------------------
Microsoft Windows 10 Pro 10.0.19041 19041                      7339572

⚡ nickmoore@nickmoore003  C:\Autolab\Configurations\Windows10                                               [19:56]
❯ Invoke-Pester .\vmvalidate.test.ps1
Pester v4.10.1
Executing all tests in '.\vmvalidate.test.ps1'

Executing script .\vmvalidate.test.ps1

  Describing Win10Ent
    [-] [Win10Ent] Should allow a PSSession but got error: The virtual machine Win10Ent is not in running state. 1.16s
      Expected $true, but got $false.
      83:             $false | Should Be $True
      at <ScriptBlock>, C:\Autolab\Configurations\Windows10\VMValidate.test.ps1: line 83
Tests completed in 4.8s
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0

WARNING: Failed to start lab. Are you running this in the correct configuration directory? 'Win10Ent' failed to start.

Failed to start the virtual machine 'Win10Ent' because one of the Hyper-V components is not running.

                                                                                                                        The Virtual Machine Management Service failed to start the virtual machine 'Win10Ent' because one of the Hyper-V        components is not running (Virtual machine ID 6B034FEE-F6D2-4C43-821B-6051681AAA6E). `

**Comment by jdhitsolutions** [comment]
If you run `Get-VM` do you see the Win10Ent virtual machine? Did you get any errors when you run `unattend-lab` or the equivalent commands? if  the Win10ENT VM is not running, can you run `Start-VM win10ent` and start it?  For some reason, the Windows 10 VMs will shut down during the configuration process and not restart. But only Windows 10. If you get the machine running again, wait a few minutes and then try running the validation test again.

**Comment by bankershours** [comment]
I was able to get it running on my local machine, the original error was produced on an Azure instance in Azure DevTest Labs.  I have to believe it's something to do with Start-Host and Hyper-V I can view the Hyper-V Manager I can see the instances off but when I try to start them I get:

Failed to start the virtual machine 'Win10Ent' because one of the Hyper-V components is missing.  I've done multiple reboots after Start-Host same error.  Instance is size Standard_A3 running Windows 10 Pro Version 2004

Same error with Start-VM Win10Ent

**Comment by jdhitsolutions** [comment]
The module was designed and intended to be run locally on a Windows 10 desktop with Hyper-V. There's no way of knowing what will work or not work when running this in Azure. Although it is clear, it doesn't look like Azure is a good choice. I'll have to update the documentation to make this clear. I doubt this will ever work in Azure and I have no way really of supporting it.

**Comment by bankershours** [comment]
@jdhitsolutions Thanks for the clarification, I’ll close this out as it is working on my local desktop.
