### ISSUE TITLE
GetItem and GetChildItem errors - HyperV version not displaying

### ISSUE THREAD

**Issue by melkinz** [pluralsight/PS-AutoLab-Env#239]
Hello, 
I'm seeing a number of errors at different points in the process of setting up the host and building the labs. 
(I'm trying to install and run labs for the Pluralsight course "The Issues of Identity and Access Management" by Dale Meredith.)

For example, after running this command: 
`C:\Autolab\Configurations\<yourconfigfolder>Setup-Lab -ignorependingreboot`
This is the result:

`Installing required DSCResource modules from PSGallery
You may need to say "yes" to a Nuget Provider
install xActiveDirectory version 3.0.0.0
install xComputerManagement version 4.1.0.0
install xNetworking version 5.7.0.0
install xDhcpServer version 2.0.0.0
install xWindowsUpdate version 2.8.0.0
install xPSDesiredStateConfiguration version 9.1.0
install xPendingReboot version 0.4.0.0
install xADCSDeployment version 1.4.0.0
install xDnsServer version 1.16.0.0
Build the .Mof files from the configs

    Directory: C:\AutoLab\configurations\MultiRole

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----       10/12/2020   3:59 PM         526664 DC1.mof                                                               
-a----       10/12/2020   3:59 PM           1118 DC1.meta.mof                                                          
-a----       10/12/2020   3:59 PM           9846 S1.mof                                                                
-a----       10/12/2020   3:59 PM           1116 S1.meta.mof                                                           
-a----       10/12/2020   3:59 PM          14642 Cli1.mof                                                              
-a----       10/12/2020   3:59 PM           1120 Cli1.meta.mof                                                         
Building the lab environment for MultiRole

Get-ChildItem : Cannot find path 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto 
Update\' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.19.1\DSCResources\xPendingReboot\DSCResources\MSFT_xPendingReb
oot\MSFT_xPendingReboot.psm1:26 char:27
+ ... dateKeys = (Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKEY_LOCAL_MACH...te\Auto Update\:String) [Get-ChildItem], ItemNotFound 
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand`

It also complains about not finding vmms.exe, even though the file does exist in the indicated directory.

`PS C:\> Get-PSAutoLabSetting
Get-Item : Cannot find path 'C:\WINDOWS\System32\vmms.exe' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\PSAutoLab\4.18.0\functions\public.ps1:149 char:28
+ ...     HyperV          = (Get-Item $env:windir\System32\vmms.exe).versio ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\System32\vmms.exe:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
 
AutoLab                     : C:\Autolab
PSVersion                   : 5.1.18362.752
PSEdition                   : Desktop
OS                          : Microsoft Windows 10 Enterprise
FreeSpaceGB                 : 876.23
MemoryGB                    : 32
PctFreeMemory               : 87.53
Processor                   : Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
IsElevated                  : True
RemotingEnabled             : True
HyperV                      : 
PSAutolab                   : 4.18.0
Lability                    : 0.19.1
Pester                      : {4.10.1, 3.4.0, 3.4.0}
PowerShellGet               : 1.0.0.1
PSDesiredStateConfiguration : 1.1`

Can you advise? I'm unsure why the HyperV field is blank. HyperV was enabled and installed prior to installing and running PS-AutoLab-Env.

**Comment by jdhitsolutions** [comment]
1. The fact that HyperV is blank is troubling. If you run `get-module hyper-v -list` you need to see version 2.0.0.0.
2. What configuration is Dale having you build?
3. Is your computer subject to any Group Policy settings?
4. You might also run `Open-PSAutolabHelp` and look at the Detailed  Setup Instructions section.

**Comment by melkinz** [comment]
Thank you for the quick response, much appreciated. 
Dale's course is a few years old, so the configuration he describes in the course has been archived in the PS Autolabs archive directory. But the "MultiRole" or "MultiRole-Sever 2016" configurations should do the trick. (He also calls for separately installing Kali Linux.)

I've been constantly referencing the excellent help manual PDF that comes with the install, but now see in the Detailed Setup instructions that O365 is not recommended, and I'm running that. I didn't take note of that while performing the "pre-check"...this must be the issue. This is a standalone PC with no AD or anything like that, so no group policy settings.

Here is the output of `get-module hyper-v -list`. Is it ok that there are two entries? 

Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules


ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Binary     2.0.0.0    Hyper-V                             {Add-VMAssignableDevice, Add-VMDvdDrive, Add-VMFibreChanne...
Binary     1.1        Hyper-V                             {Add-VMDvdDrive, Add-VMFibreChannelHba, Add-VMHardDiskDriv...


Thanks again for your quick response. I guess I'll need to disconnect from Office 365.

**Comment by jdhitsolutions** [comment]
This makes more sense now. I don't do much with O365 but I think what is happening is that you are logging on with an account that doesn't have true local admin rights. That's why you can't see the HKEY_LOCAL_MACHINE registry key and probably the vmms.exe file.

**Comment by jdhitsolutions** [comment]
Is this an issue that needs to remain open?
