### ISSUE TITLE
Get-LabSummary fails if VM has no Lability_Media

### ISSUE THREAD

**Issue by andreasjordan** [pluralsight/PS-AutoLab-Env#245]
I setup a lab config with some maschines that don't have a Lability_Media entry and thus use the global entry from AllNodes. 

When using Get-LabSummary the command fails at public.ps1:83 with "Fehler beim Indexvorgang. Der Arrayindex wurde als NULL ausgewertet." (sorry, german system - Index operation failed. The array index was evaluated as NULL.) because of line 88: $media[$_.lability_media] where $_.lability_media is null.
Just changing the configuration file and adding the Lability_Media entries let the command work again fine.

Sorry, I don't have an idea for a quick fix, but still want to report this.

**Comment by andreasjordan** [comment]
Get-PSAutolabSetting says:
```
AutoLab                     : C:\Autolab
PSVersion                   : 5.1.18362.1171
PSEdition                   : Desktop
OS                          : Microsoft Windows 10 Pro
FreeSpaceGB                 : 271,71
MemoryGB                    : 32
PctFreeMemory               : 75,54
Processor                   : Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
IsElevated                  : True
RemotingEnabled             : False
HyperV                      : 10.0.18362.1130
PSAutolab                   : {4.18.0, 4.17.0, 4.16.0, 4.15.0}
Lability                    : 0.19.1
Pester                      : {4.10.1, 3.4.6, 3.4.0}
PowerShellGet               : 2.2.5
PSDesiredStateConfiguration : 1.1
```

The configuration is one that I build my own based on the PowerShellLab. So, yes - not one of the supported ones. So it's ok that it only works with every maschine having its own Lability_Media. 

Just wanted to let you know.

**Comment by jdhitsolutions** [comment]
I see now. I misread your original issue. You are correct. If there is no Lability_Media entry, the configuration will fail. This isn't a bug but by design. The setup process has to know what media to use to setup the virtual machine.

**Comment by andreasjordan** [comment]
Just to be clear: The setup of the lab works fine, because Lability works with inheritance and uses the general setting for Lability_Media from the section AllNodes. It's only the command Get-LabSummary that reads the configuration but does not use inheritance as a fallback if the maschine has no Lability_Media.

**Comment by jdhitsolutions** [comment]
Got it. I can address this issue in the next release. I'm re-opening the issue for tracking purposes.

**Comment by jdhitsolutions** [comment]
This should be handled better in v4.19.0 which has been published to the PowerShell Gallery.

**Comment by andreasjordan** [comment]
Yes, works very well. Thank you for the fast fix.
