### ISSUE TITLE
Unable to configure PSAutolab

### ISSUE THREAD

**Issue by jschtor** [pluralsight/PS-AutoLab-Env#246]
Hello,

In the first step (Install-Module PSAutolab -force) i get the error below
_________________________________________________________________________________________________
PackageManagement\Install-Package : A Microsoft-signed module named 'Pester' with version '3.4.0' that was
previously installed conflicts with the new module 'Pester' from publisher 'CN=DigiCert Assured ID Root CA,
OU=www.digicert.com, O=DigiCert Inc, C=US' with version '4.10.1'. Installing the new module may result in system
instability. If you still want to install or update, use -SkipPublisherCheck parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Packa
   ge], Exception
    + FullyQualifiedErrorId : PublishersMismatch,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.Packag
   eManagement.Cmdlets.InstallPackage

__________________________________________________________________________________________________
Additional details:
- Tried editing the script adding the -SkipPublisherCheck parameter in the line requested, wihtout any changes in results.
- Execution policy was set to unrestricted
- Using W10 Pro, 20H2 (OS Build 19042.685)
PS C:\WINDOWS\system32> $Host.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  610

PS C:\WINDOWS\system32> $PSVersiontable
Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
___________________________________________________________________________________________________
I hope this is an easy one, as i can't advance at all 

Thanks in advance!

**Comment by jdhitsolutions** [comment]
This is a known problem. Run the install like this:

```powershell
install-module psautolab -SkipPublisherCheck -force
```
