### ISSUE TITLE
Powershell lab servers don't come up but DOS-prompt

### ISSUE THREAD

**Issue by jschtor** [pluralsight/PS-AutoLab-Env#247]
Hello,
I have installed the lab, but all servers come up with DOS logon possibility, but there is no windows available, neither RDP nor Hyper-V connection. Attached is a sample image. It happens the same on all servers, only workstation running W10 seem to work

DOM1, SRV1, SRV2, SRV3 are affected 

I was trying to identify issue without success as lab tests don't report any error. Restarting lab, even creating lab again from 0 after a fresh local machine format and W10 installed didn't make it either.

I have no idea of what can be causing that, can you please guide me? Thanks

Let me know what information you need.

My host is running on W10 Pro 2020H2 with latest updates installed.
120GB SSD extra drive for Lab (D:) drive, 16GB RAM

PS D:\AutoLab\Configurations\PowerShellLab> Get-PSAutoLabSetting

AutoLab                     : D:\AutoLab
PSVersion                   : 5.1.19041.610
PSEdition                   : Desktop
OS                          : Microsoft Windows 10 Pro
FreeSpaceGB                 : 69.32
MemoryGB                    : 16
PctFreeMemory               : 28,42
Processor                   : Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
IsElevated                  : True
RemotingEnabled             : True
NetConnectionProfile        : Public
HyperV                      : 10.0.19041.1
PSAutolab                   : 4.19.0
Lability                    : 0.19.1
Pester                      : {4.10.1, 3.4.0}
PowerShellGet               : 1.0.0.1
PSDesiredStateConfiguration : 1.1

![DOM1error](https://user-images.githubusercontent.com/76781484/105993553-d9cf2100-60a6-11eb-8407-63f50563bdac.PNG)
![SRV3error](https://user-images.githubusercontent.com/76781484/105993561-db98e480-60a6-11eb-8072-77cbd8c059b9.PNG)

Thanks a lot in advance for your help!!

**Comment by jdhitsolutions** [comment]
The servers are all running Server Core. There is no GUI. In the PowerShellLab configuration, the idea is that you'll manage everything remotely from the Wndows 10 desktop, most likely using PowerShell.
