### ISSUE TITLE
Get-PSAutoLabSetting

### ISSUE THREAD

**Issue by toddfarrjr** [pluralsight/PS-AutoLab-Env#248]
Get-PSAutolabsetting returns values for FreeSpaceGB and others with extra charaters '[92m'  '[0m'

![image](https://user-images.githubusercontent.com/78820170/107416138-245a8f80-6ae2-11eb-90d6-f8d9fea02c49.png)

**Comment by jdhitsolutions** [comment]
If you are running this in the PowerShell ISE that is to be expected. Those are ANSI sequences that normally look like this in the regular console.  But I think I can add something to detect if running in the ISE.

![image](https://user-images.githubusercontent.com/12089920/107448991-c2fde500-6b10-11eb-9d81-c39c00c63841.png)
