### ISSUE TITLE
Unable to setup labs

### ISSUE THREAD

**Issue by perschulze** [pluralsight/PS-AutoLab-Env#249]
I used to be able to create labs without any issue, but now I constantly get this error, no matter what configuration I try to setup:

`Failed to start lab configuration.
Set-LabVMDiskFileResource : Cannot bind argument to parameter 'VhdDriveLetter' because it is an empty string.
At line:82 char:74
+ ... MDiskFileResource @PSBoundParameters -VhdDriveLetter $vhdDriveLetter;
    + CategoryInfo          : InvalidData: (:) [Set-LabVMDiskFileResource], ParameterBindingValidationExce
   ption
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Set-LabVMDiskFileResource                                                                           `

I have tried to start from scratch, verified my setup etc. but I just can't seem to figure out what the issue is.

My AutoLab Settings:
AutoLab                     : C:\Autolab
PSVersion                   : 5.1.19041.610
PSEdition                   : Desktop
OS                          : Microsoft Windows 10 Pro
FreeSpaceGB                 : 223.16
MemoryGB                    : 32
PctFreeMemory               : 86,18
Processor                   : Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
IsElevated                  : True
RemotingEnabled             : True
NetConnectionProfile        : Private
HyperV                      : 10.0.19041.561
PSAutolab                   : 4.19.0
Lability                    : {0.19.1, 0.19.0, 0.18.0}
Pester                      : {4.10.1, 3.4.0}
PowerShellGet               : 2.2.4.1
PSDesiredStateConfiguration : 1.1

**Comment by jdhitsolutions** [comment]
What lab configuration are you trying to set up?

**Comment by perschulze** [comment]
Hi

I have tried them all by now. It used to work without any issue. 

ISO file downloads
ISO file mounts and a  mastervirtualharddisk is created
The virtual Machine gets created
A VMVirtualHardDisk get's created, but is only 4.096KB. The the error happens.
I can boot the virtual machine, but it's not in a configured state.

**Comment by jdhitsolutions** [comment]
And it used to work on this same machine? This is very odd. Do you have any other virtual machines on this system?

**Comment by perschulze** [comment]
Yes it worked fine on the same machine for about a month or so ago. I then wanted to rebuild a lab, so I wiped it and wanted to create a new one and then i just keept getting the before mentioned error. Where it fails with the Set-LabVMDiskFileResource because of a missing drive letter.

And yes I have 1 other virtual machine on the system.

**Comment by jdhitsolutions** [comment]
The module hasn't changed in a while so I'm at a loss to figure out why you are having issues now. Wipe the last lab you built. Then run `Open-PSAutolabHelp` and look through the Detailed Setup Instructions.  Then, start a PowerShell transcript, and run a manual configuration setup using -Verbose. I expect you'll get an error after running `Setup-Lab`.  Stop the transcript and upload the file as an attachment here.  Then run `dir c:\autlolab -file -recurse | export-clixml <somepath>\lab.xml and upload the XML file so I can see what you are ending up with.

**Comment by perschulze** [comment]
Hi Jeff

I have attached the transscript and the xml file in the zip file.
[xmlAndTransscript.zip](https://github.com/pluralsight/PS-AutoLab-Env/files/6006764/xmlAndTransscript.zip)

**Comment by jdhitsolutions** [comment]
I've identified where the error is originating but I can't figure out why. Based on what you showed me everything looks normal. You haven't edited or customized any of the files have you?  Let's try one more thing. Change to the MultiRole folder and run these commands:

```powershell
$c = Import-PowerShellDataFile .\VMConfigurationData.psd1
get-labmedia -id $c.allnodes[0].lability_media
```

You should see something like this:

![image](https://user-images.githubusercontent.com/12089920/108513756-0256cf00-7291-11eb-9abe-40748ef9ece6.png)

**Comment by perschulze** [comment]
Hi Jeff

No I had not made any configuration changes.

After trying all kind of clearing out the modules, uninstalling Hyper-v, creating a new user account etc. I gave up and reinstalled Windows. Now it's working again. So what the reason for the issue was, remains a mystery.

Thanks for your time and help.

**Comment by jdhitsolutions** [comment]
Based on the errors the first thing that came to mind was some sort of file corruption. Or the i3 processor wasn't up the job. Your system has plenty of memory but I'd be concerned about how well it i3 handles the virtualization load. But, I'm glad you found a resolution.
