### ISSUE TITLE
Unable to wipe lab

### ISSUE THREAD

**Issue by techgururepublic** [pluralsight/PS-AutoLab-Env#252]
![PSautolab](https://user-images.githubusercontent.com/85156177/126126816-ab16fcc1-4bdc-419a-95cb-d5d965d106f2.JPG)
Hi,

I tried to install PSAutolab by following the instructions and discovered that my C drive was not having ample space for 1024 MB so I decided to wipe off the lab but it produces an error that says Hyper-V is not able to find a virtual machine with name "S1" 
![PSautolab wipe](https://user-images.githubusercontent.com/85156177/126127224-716e87ad-bf85-49fa-9cf0-2898f9027f61.JPG)
Hope you can help me through the wiping out the Autolab.

**Comment by jdhitsolutions** [comment]
So you started to build a lab and then it failed partway through? You actually might not have anything to worry about. In the SingleServer directory, you can manually delete any .MOF files. Then run `Get-VM` and see if there is a VM called S1. There probably isn't. At this point you can continue the uninstall process. Run `Open-PSAutolabHelp` and look at the `Removing PSAutolab` section for more help. Just be sure to close the PDF before you attempt to uninstall it.
