### ISSUE TITLE
Failing to Validate Lab: Should allow PSSession but got an error

### ISSUE THREAD

**Issue by ThrowAwayJuriFBI** [pluralsight/PS-AutoLab-Env#253]
> AutoLab                     : C:\Autolab
> PSVersion                   : 5.1.18362.1714
> PSEdition                   : Desktop
> OS                          : Microsoft Windows 10 Enterprise
> FreeSpaceGB                 : 878.37
> MemoryGB                    : 64
> PctFreeMemory               : 87.11
> Processor                   : Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
> IsElevated                  : True
> RemotingEnabled             : True
> NetConnectionProfile        : Public
> HyperV                      : 10.0.18362.1049
> PSAutolab                   : 4.20.0
> Lability                    : 0.20.0
> Pester                      : {4.10.1, 3.4.0}
> PowerShellGet               : 1.0.0.1
> PSDesiredStateConfiguration : 1.1
> 

> PS C:\Autolab\Configurations\Windows10> Invoke-Pester .\VMValidate.test.ps1
> Pester v4.10.1
> Executing all tests in '.\VMValidate.test.ps1'
> 
> Executing script .\VMValidate.test.ps1
> 
>   Describing Win10Ent
>     [-] [Win10Ent] Should allow a PSSession but got error: An error has occurred which Windows PowerShell cannot handle. A remote session might have ended. 11ms
>       Expected $true, but got $false.
>       83:             $false | Should Be $True
>       at <ScriptBlock>, C:\Autolab\Configurations\Windows10\VMValidate.test.ps1: line 83
> Tests completed in 30.46s
> Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
> PS C:\Autolab\Configurations\Windows10> Get-PSAutoLabSetting

I'm not really sure how to drill down on this but I've been trying to get PSAutoLab up and running all day with no luck. Every attempt to validate the lab has failed. I'm using just the Win10Ent machine, keeping it bare bones as possible. I have tried stopping and starting the VM via the Stop-VM and Start-VM cmdlets. I've also tried rebooting the physical desktop hosting the VMs to no avail. 
Any idea what I should be checking at this point?

**Comment by jdhitsolutions** [comment]
First, I apologize for missing this issue. Github used to notify me by email when there was a new issue, but I appear to be missing or no longer receiving notifications.  Validation aside, can you open a remote desktop session to the VM?

**Comment by jdhitsolutions** [comment]
I think I see why you are getting the remoting error. Your network connection is set to public and by default, PowerShell remoting doesn't go over those networks. You can try resetting it in an elevated PowerShell session.

```powershell
get-netconnectionprofile | where networkcategory -eq public| Set-NetConnectionProfile -NetworkCategory Private
```

**Comment by ThrowAwayJuriFBI** [comment]
Now I'm the one missing things. Ultimately I had some severe hardware
issues compounding my struggles with getting PSAutoLab up and running and
had to get a new workstation. I can't attest to what exactly was the root
cause, but trying the whole process again with a fresh workstation ended up
working out, so it's all good as far as I'm concerned.

While I've got you on the line though, I'd just like to sincerely thank you
for two of your books I've recently finished reading. Powershell in a Month
of Lunches and Powershell Scripting in a Month of Lunches are far and away
the best two technical books I have ever read. I had a few years of
experience using Powershell prior to my boss handing me those and I thought
I had a pretty good handle on it, but reading those two books did wonders
for my understanding of it. It was exactly what I needed as I try to steer
my career in a direction that will afford me more opportunities to spend
all day tinkering with Powershell. So thank you.

**Comment by jdhitsolutions** [comment]
I'm glad you got everything worked out. Thank you for your kind words regarding the books. If you've read those, you might take a look at [The PowerShell Practice Primer](https://leanpub.com/psprimer) and [The PowerShell Scripting and Toolmaking Book](https://leanpub.com/powershell-scripting-toolmaking/)
