### ISSUE TITLE
PowerShell Error - 'Cannot build MOF files from the configs'

### ISSUE THREAD

**Issue by jc0081** [pluralsight/PS-AutoLab-Env#254]
Please see the screenshots below ...

![image](https://user-images.githubusercontent.com/90786053/133468261-869a4499-37ec-4258-bc13-f8dd777710f7.png)

![image](https://user-images.githubusercontent.com/90786053/133468375-b13e75e7-6918-4a2a-83b1-bda216fd5062.png)

Any suggestion on what to do next?

**Comment by jdhitsolutions** [comment]
First, you are probably going to run low on disk space and barely have enough memory. Try one of the single server configurations and see if you get the same error. Then I will know if it is a broader problem or limited to this lab

**Comment by jc0081** [comment]
I moved over to a different machine with more space and it looks like it's running now. Plus, I ran the command 'Setup-Lab -ignorependingreboot' . Stay tuned!

**Comment by jdhitsolutions** [comment]
That's good. I still may need to tweak a few files for the Multirole-Server-2016 lab. Let me know if you still encounter problems.

**Comment by jc0081** [comment]
Update ... I switched over to a desktop with more firepower and reinstalled AutoLab. In the process, I ran into this error ...
![image](https://user-images.githubusercontent.com/90786053/133914436-8f6fab55-e499-46a0-b121-f7da01a2e3c5.png)

Don’t know why, but the “Could not find the module '<xPendingReboot, 0.4.0.0>'.” was not downloading. So, I went to (https://www.powershellgallery.com/packages/xPendingReboot/0.4.0.0) and installed it directly with Install-Module -Name xPendingReboot. 

Afterwards, I re-ran setup-lab IgnorePendingReboot and it began to install the ISOs!

Maybe this module was missing? Anyway, just thought I'd let you know.

**Comment by jdhitsolutions** [comment]
That is the bug I found that I am fixed. But you came up with the workaround on your own.

**Comment by jc0081** [comment]
I had another question ... let me know if you want me to create a new post about it ... 

Now that I have the lab setup using the "MultiRole-Server-2016" setup, I noticed that these servers are setup with 'core' (yuck!). Can I somehow 'add' a new server/servers to this lab with a 2019 GUI version? Or do I have to rebuild the entire lab, pointing the ISOs (in the PDS1 file) to the GUI version of Windows Server?

**Comment by jdhitsolutions** [comment]
There are steps in the Detailed Setup Instructions on how to customize a lab. But yes, you would have to rebuild the lab. Using Server Core is actually to your advantage because it means you don't need as much RAM. I'm working on a new release to the module. I can create a MultiRole-Server-GUI configuration that will use Windows Server 2019 and all GUI installs.

**Comment by jc0081** [comment]
Sounds good. Thanks!

**Comment by jdhitsolutions** [comment]
Update to v4.21.0. Run `Refresh-Host`. In the configuration folder, you'll see a new Multirole configuration.

**Comment by jc0081** [comment]
Excellent! I really appreciate it!
