### ISSUE TITLE
Installation of PS-AutoLab-env

### ISSUE THREAD

**Issue by AObadeyi** [pluralsight/PS-AutoLab-Env#255]
Hi Trying to install PS-Autolab-ENV displaying an error. You video was published 2017 not sure if the process of installation has changed.  please see below error.

PS C:\Users\aobadeyi> cd C:\PS-AutoLab-Env-master

PS C:\PS-AutoLab-Env-master> .\setup-host.ps1
.\setup-host.ps1 : The term '.\setup-host.ps1' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\setup-host.ps1
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\setup-host.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jdhitsolutions** [comment]
Installation instructions are very different. Start with the README file in this repository.

**Comment by jdhitsolutions** [comment]
Closing as inactive and presumed resolved.
