### ISSUE TITLE
PS-Autolab-env

### ISSUE THREAD

**Issue by AObadeyi** [pluralsight/PS-AutoLab-Env#256]
Please see below error message

PS C:\Users\aobadeyi> cd \

PS C:\> Get-NetNat LabNat
Get-NetNat : No MSFT_NetNat objects found with property 'Name' equal to 'LabNat'.  Verify the value of the property and 
retry.
At line:1 char:1
+ Get-NetNat LabNat
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (LabNat:String) [Get-NetNat], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_Name,Get-NetNat

**Comment by jdhitsolutions** [comment]
Did you run `Setup-Host`? What is the result from `Get-PSAutolabSetting`?

**Comment by jdhitsolutions** [comment]
Closing as inactive and presumed resolved.
