### ISSUE TITLE
MOF Errors

### ISSUE THREAD

**Issue by jstrick1028** [pluralsight/PS-AutoLab-Env#257]
Hello!
I am trying to get AutoLab working after following the steps for updating from an older version: [https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md](url)

When trying to setup the Single Server 2019 GUI config I get an "Invalid MOF Definition for node 'S1'" error.
![Screenshot 2021-12-07 150509](https://user-images.githubusercontent.com/16136708/145109515-e401bb5f-d13c-49e9-b142-ba7e22dd0aa9.jpg)

![Screenshot 2021-12-07 150425](https://user-images.githubusercontent.com/16136708/145109539-3b44c6bd-02ab-4e1b-a99c-e18f6fb98e45.png)

**Comment by jdhitsolutions** [comment]
I'd suggest first running `Wipe-Lab` to reset the configuration. Then run `Refresh-Host` to copy the configuration files from the module source. Then try running the module again. If this still fails, post a directory listing.

**Comment by jstrick1028** [comment]
Wipe-Lab was unsuccessful. 
![Screenshot 2021-12-08 103519](https://user-images.githubusercontent.com/16136708/145247034-f9d10c19-391c-4853-8506-51ada61f1929.png)

Here is a directory listing of the SingleServer-GUI-2019 folder
![Screenshot 2021-12-08 103546](https://user-images.githubusercontent.com/16136708/145247180-31c139bd-9526-4135-aa5d-4d320baaf799.png)

**Comment by jdhitsolutions** [comment]
Don't worry about the error. You probably never got the VM created. Post the contents of the s1.mof.error file and then you can delete it. The files look right, but I'd still suggest running `Refresh-Host` then trying to set up the lab again. I know the configuration works. Just need to figure out what is different on this computer.

**Comment by jstrick1028** [comment]
S1.mof.error

/*
@TargetNode='S1'
@GeneratedBy=james
@GenerationDate=12/08/2021 10:50:15
@GenerationHost=VM-SERVER
*/

instance of MSFT_RegistryResource as $MSFT_RegistryResource1ref
{
ResourceID = "[Registry]TLS";
 ValueName = "SchUseStrongCrypto";
 Key = "HKLM:\\SOFTWARE\\Wow6432Node\\Microsoft\\.NetFramework\\v4.0.30319";
 Ensure = "Present";
 SourceInfo = "D:\\AutoLab\\Configurations\\SingleServer-GUI-2019\\VMConfiguration.ps1::45::9::registry";
 ValueType = "Dword";
 ModuleName = "PSDesiredStateConfiguration";
 ValueData = {
    "1"
};

ModuleVersion = "1.1";

 ConfigurationName = "AutoLab";

};
instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]PS2";
 Ensure = "Absent";
 SourceInfo = "D:\\AutoLab\\Configurations\\SingleServer-GUI-2019\\VMConfiguration.ps1::57::9::WindowsFeature";
 Name = "PowerShell-V2";
 ModuleName = "PSDesiredStateConfiguration";

ModuleVersion = "1.1";

 ConfigurationName = "AutoLab";

};
instance of MSFT_xIPAddress as $MSFT_xIPAddress1ref
{
ResourceID = "[xIPAddress]PrimaryIPAddress";
 InterfaceAlias = "Ethernet";
 AddressFamily = "IPv4";
 SourceInfo = "D:\\AutoLab\\Configurations\\SingleServer-GUI-2019\\VMConfiguration.ps1::67::13::xIPAddress";
 ModuleName = "xNetworking";
 IPAddress = {
    "192.168.3.19"
};
 ModuleVersion = "5.7.0.0";

 ConfigurationName = "AutoLab";

};
instance of MSFT_xDefaultGatewayAddress as $MSFT_xDefaultGatewayAddress1ref
{
ResourceID = "[xDefaultGatewayAddress]PrimaryDefaultGateway";
 AddressFamily = "IPv4";
 SourceInfo = "D:\\AutoLab\\Configurations\\SingleServer-GUI-2019\\VMConfiguration.ps1::74::17::xDefaultGatewayAddress";
 Address = "192.168.3.1";
 ModuleName = "xNetworking";
 InterfaceAlias = "Ethernet";
 ModuleVersion = "5.7.0.0";

 ConfigurationName = "AutoLab";

};
instance of MSFT_xDNSServerAddress as $MSFT_xDNSServerAddress1ref
{
ResourceID = "[xDNSServerAddress]PrimaryDNSClient";
 AddressFamily = "IPv4";
 SourceInfo = "D:\\AutoLab\\Configurations\\SingleServer-GUI-2019\\VMConfiguration.ps1::82::17::xDnsServerAddress";
 Address = {
    "1.1.1.1"
};
 ModuleName = "xNetworking";
 InterfaceAlias = "Ethernet";
 ModuleVersion = "5.7.0.0";

 ConfigurationName = "AutoLab";

};
instance of MSFT_RegistryResource as $MSFT_RegistryResource2ref
{
ResourceID = "[Registry]RDP";
 ValueName = "fDenyTSConnections";
 Key = "HKLM:\\System\\ControlSet001\\Control\\Terminal Server";
 Ensure = "Present";
 SourceInfo = "D:\\AutoLab\\Configurations\\SingleServer-GUI-2019\\VMConfiguration.ps1::139::9::Registry";
 ValueType = "Dword";
 ModuleName = "PSDesiredStateConfiguration";
 ValueData = {
    "0"
};

ModuleVersion = "1.1";

 ConfigurationName = "AutoLab";

};
instance of MSFT_xFirewall as $MSFT_xFirewall1ref
{
ResourceID = "[xFirewall]RemoteDesktop-UserMode-In-TCP";
 Enabled = "True";
 SourceInfo = "D:\\AutoLab\\Configurations\\SingleServer-GUI-2019\\VMConfiguration.ps1::151::13::xFirewall";
 Name = "RemoteDesktop-UserMode-In-TCP";
 ModuleName = "xNetworking";
 ModuleVersion = "5.7.0.0";

DependsOn = {

    "[Registry]RDP"};

 ConfigurationName = "AutoLab";

};
instance of MSFT_xFirewall as $MSFT_xFirewall2ref
{
ResourceID = "[xFirewall]RemoteDesktop-UserMode-In-UDP";
 Enabled = "True";
 SourceInfo = "D:\\AutoLab\\Configurations\\SingleServer-GUI-2019\\VMConfiguration.ps1::151::13::xFirewall";
 Name = "RemoteDesktop-UserMode-In-UDP";
 ModuleName = "xNetworking";
 ModuleVersion = "5.7.0.0";

DependsOn = {

    "[Registry]RDP"};

 ConfigurationName = "AutoLab";

};
instance of MSFT_xFirewall as $MSFT_xFirewall3ref
{
ResourceID = "[xFirewall]RemoteDesktop-Shadow-In-TCP";
 Enabled = "True";
 SourceInfo = "D:\\AutoLab\\Configurations\\SingleServer-GUI-2019\\VMConfiguration.ps1::151::13::xFirewall";
 Name = "RemoteDesktop-Shadow-In-TCP";
 ModuleName = "xNetworking";
 ModuleVersion = "5.7.0.0";

DependsOn = {

    "[Registry]RDP"};

 ConfigurationName = "AutoLab";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";
 

                        MinimumCompatibleVersion = "1.0.0";
 

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 

                        Author="james";
 

                        GenerationDate="12/08/2021 10:50:15";
 

                        GenerationHost="VM-SERVER";
 

                        Name="AutoLab";


                    };

**Comment by jstrick1028** [comment]
Deleted the AutoLab folder and ran `Setup-Host -DestinationPath D:\AutoLab` to recreate it.
Navigated to D:\AutoLab\Configurations\SingleServer-GUI-2019 and ran setup-lab -ignorependingreboot
Still received MOF errors.

**Comment by jdhitsolutions** [comment]
You only need to run `Setup-Host` once.  Although, I suppose this should give you the same end result as running `Refresh-Host`. I looked again at the error and think you might have a DSC Resource conflict.  You said you upgraded from a previous version. While in the folder, run `Test-LabDSCResource`.

![image](https://user-images.githubusercontent.com/12089920/145268532-1d07c1f7-c7f7-4271-925f-8d062313d2b3.png)

I seem to recall an issue with the xNetworking module. If you have a version older than 5.7.0.0, PowerShell may be using the older version which doesn't recognize one of the settings in the configuration file. If you have older versions of xNetworking you should be able to uninstall them.

```powershell
Uninstall-Module networking -requiredversion X.X.X.X
```

They try again.

**Comment by jdhitsolutions** [comment]
I'm pretty sure this is your problem. https://github.com/pluralsight/PS-AutoLab-Env#multiple-dsc-resources

**Comment by jstrick1028** [comment]
You are correct! I uninstalled the older versions to make my config match the versions in your screenshot and it is downloading the ISOs now. Thanks!

**Comment by jdhitsolutions** [comment]
Great. This is only going to be an issue for the handful of people who set up labs with a legacy version of this module. Glad you are up and running.
