### ISSUE TITLE
.\Setup-Host.ps1 results in an error

### ISSUE THREAD

**Issue by AiPeeKings** [pluralsight/PS-AutoLab-Env#258]
Hello Jeff,

I have just started your beginner PowerShell course on PluralSight.

I believe I have followed all yours steps passionately but I get an error when I type in this command .\Setup-Host.ps1 after changing my directory to PS C:\PS-AutoLab-Env-master> as you instructed.

Yet I downloaded. extracted and saved the PS-AutoLab-Env-master folder in my C: drive.

Here is the error message I got:
----------------------
PS C:\PS-AutoLab-Env-master> .\Setup-Host.ps1
.\Setup-Host.ps1 : The term '.\Setup-Host.ps1' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ .\Setup-Host.ps1
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Setup-Host.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

------------------------
How would you resolve this problem please?

Cheers, AiPeeKings

**Comment by jdhitsolutions** [comment]
I suspect you are following old instructions and downloaded the module from Github. That is not the correct process anymore.  You should delete everything you downloaded and start all over.  You need to install the module from the PowerShell Gallery.

Run this in Windows PowerShell:

```powershell
Install-Module PSAutolab -force -SkipPublisherCheck
```

Then you can run:

```powershell
Setup-Host
```

Read https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Detailed-Setup-Instructions.md for detailed instructions.


Answer yes to any prompt.

**Comment by jdhitsolutions** [comment]
closing as inactive and presumed resolved
