### ISSUE TITLE
Setup-Host Exception

### ISSUE THREAD

**Issue by williammoore175** [pluralsight/PS-AutoLab-Env#259]
Good evening.  I have started your Powershell - Your First Day course and have tried to run the setup instructions (updated).  But I ran into the following exception:

PS C:\> Setup-Host -DestinationPath C:\Autolab
Setup-Host : The 'Setup-Host' command was found in the module 'PSAutoLab', but the module could not be loaded. For
more information, run 'Import-Module PSAutoLab'.
At line:1 char:1
+ Setup-Host -DestinationPath C:\Autolab
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Setup-Host:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\> Import-Module PSAutoLab
Import-Module : File C:\Program Files\WindowsPowerShell\Modules\Lability\0.20.0\Lability.psm1 cannot be loaded because
running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ Import-Module PSAutoLab
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand

It appears running scripts has been disabled.  Do you have advisement on how to get it re-enabled.  Thank you.

**Comment by jdhitsolutions** [comment]
Looks like you need to run `Set-ExecutionPolicy RemoteSigned -force` in an elevated PowerShell session.

**Comment by jdhitsolutions** [comment]
Closing as inactive and presumably resolved.
