### ISSUE TITLE
NetConnectionProfile is unknown

### ISSUE THREAD

**Issue by jooshyboy** [pluralsight/PS-AutoLab-Env#262]
![CNtWIOPrsE](https://user-images.githubusercontent.com/104049495/164145715-ad5c86a0-5deb-466e-906f-06b71f343f55.png)

When I run the unattend-lab I get a series of errors. Running Get-PSAutoLabSetting shows that the netconnectionprofile isn't set to private. Is there a way to change this to private that I'm missing? This is my home PC running Windows 10 Pro. On a workgroup, no domain.

Thanks!

**Comment by jdhitsolutions** [comment]
A value of `unknown` makes me think remoting isn't setup properly. What do you get when running `Get-NetConnectionprofile -interfacealias *LabNet*` I'd also suggest re-enabling PowerShell remoting in an elevated session: `enable-psremoting -force` then trying setup again. If setup if failing, the virtual switch may not be created which would account for what you are seeing. If setup still fails after enabling remoting again, post the errors. I think that is what we need to address.

**Comment by jooshyboy** [comment]
I appreciate the timely response. That was a factor in my lab setup issue. I did enable remoting and reran the however the network profile was set to public. Easy enough to change to private and now I'm cooking with gas. 

Thanks so much! Excited to start watching your courses.

**Comment by jdhitsolutions** [comment]
Good to hear.
