### ISSUE TITLE
NetConnectionProfile is unknown

### ISSUE THREAD

**Issue by Ap0ll0-F1ght3R** [pluralsight/PS-AutoLab-Env#263]
I am having the same issue as #262 but your recommendation posted to the other user did not work for me. Is there any other recommended trouble-shooting I could try? How specifically do I set the network connection profile for LabNet to Private for example. Also, in running Get-netconnectionprofile -interfacealias *labnet* command I get no value returned.  
Thank you.
![Capture](https://user-images.githubusercontent.com/55990601/164950696-dc3e1c8d-905e-4005-b65f-38609adf708d.PNG)
?

**Comment by aurelianbaetu** [comment]
Try placing * before and after the interface alias. Ex: Get-netconnectionprofile -interfacealias *labnet*
Most probably the alias is vEthernet (LabNet)
Next, you can use the following command to set it on Private: Set-NetConnectionProfile -InterfaceIndex <index_nr> -NetworkCategory Private

**Comment by Ap0ll0-F1ght3R** [comment]
Thanks for the help. Turns out it was as simple as not using unattend-lab and instaed use set-lab.   For whatever reason the unattend-lab command did not work for me.
