### ISSUE TITLE
Errors w/Nano

### ISSUE THREAD

**Issue by concentrateddon** [pluralsight/PS-AutoLab-Env#62]
First:
You should do a check to see if Enable-PSRemoting exists in Setup-Host; Nano server doesn't include it and enables Remoting by default.

Then:
Nano can't explicitly install Hyper-V; you might consider checking that so you're not tossing errors. I'm getting "WARNING: [6:54:19 PM] DSC resource 'Test-WindowsFeatureTargetResource' failed with
errror 'The term 'Test-WindowsFeatureTargetResource' is not recognized as the name of
 a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.'." a bunch. Bear in mind that Nano lacks Get-WindowsFeature, which is what I suspect's going on under the hood.

Additionally:
Get-ItemProperty : Cannot find path 'HKLM:\SYSTEM\CurrentControlSet\Control\ComputerName\ActiveComputerName' because
it does not exist. At C:\Program Files\WindowsPowerShell\Modules\Lability\0.10.1\DSCResources\xPendingReboot\DSCResources\MSFT_xPendingReb
oot\MSFT_xPendingReboot.psm1:35 char:28
+ ... uterName = (Get-ItemProperty 'hklm:\SYSTEM\CurrentControlSet\Control\ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SYSTEM\Cu...iveComputerName:String) [Get-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand

That appears to be in Lability. I'm not sure what-all else this will end up breaking.

**Comment by theJasonHelmick** [comment]
Will explore Nano as the host in the coming weeks
