### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by theJasonHelmick** [pluralsight/PS-AutoLab-Env#66]
* Add config to join Nano to domain
* Set Client trusted hosts to *
   (this is so client can remote to nano not joined to domain)
* Add documentation that remoting to nano requires -Credential

**Comment by jdhitsolutions** [comment]
I think every image should run Update-Help as part of Setupcomplete.cmd. I realize that servers most likely don't need updated help, but it is very handy to have when you do need it. And I have found myself in that situation more than once.

**Comment by theJasonHelmick** [comment]
This is in the plan for the future release
