### ISSUE TITLE
Win10 Client Wish List

### ISSUE THREAD

**Issue by jdhitsolutions** [pluralsight/PS-AutoLab-Env#67]
This is a wish list for the Windows 10 client configuration.

1. Automatic first login to get through the "finishing your setup".
2. configure Internet Explorer as default browser instead of Edge.  You can't use Edge when logged on as Admin.
3. find a way to make it easy to deploy files to the client.
4. I'd love to be able to deploy an app to the client like VSCode

Nothing here is a requirement but they are items that would make the process much easier. No expectations but wanted to at least get these recorded while thinking of them.

**Comment by theJasonHelmick** [comment]
Agreed -- 2 should be a registry hack -- easy enough

3,4 are already available - I just haven't documented them -- I put in place to install PowerShell 6 --- can add vscode as an application example rather than just a windows update.

1.  Not sure how to accomplish this.... will have to think about it.

**Comment by jdhitsolutions** [comment]
It used to be possible to add an entry to the unattend.xml to do a one-time auto logon.  What I don't know if that kind of logon is considered "interactive" or whatever Windows 10 needs to initiate the "finishing your setup" experience.

**Comment by jdhitsolutions** [comment]
This is the XML setting for unattend logon

<AutoLogon>
   <Password>
      <Value>MyPassword</Value>
   </Password>
   <Domain>FabrikamDomain</Domain>
   <Enabled>true</Enabled>
   <LogonCount>2</LogonCount>
   <Username>MyUserName</Username>
</AutoLogon>

https://technet.microsoft.com/en-us/library/cc766375(v=ws.10).aspx

**Comment by jdhitsolutions** [comment]
The pull request I submitted will make it easier to deploy files and install applications.

**Comment by theJasonHelmick** [comment]
Review and investigating list. Agree on the need of this list. Will add to future release.
