### ISSUE TITLE
Match time zone to host

### ISSUE THREAD

**Issue by jdhitsolutions** [pluralsight/PS-AutoLab-Env#68]
I would like the setup process to set the time zones on all servers to the time zone of the host.  If my Hyper-V host is using Eastern time then all of the servers in the lab domain should also be Eastern time. This shouldn't be that hard to make the default behavior. 

I have to think the need to specify a different time zone would be an exception but perhaps other people have an opinion on that. 

Posting this as a separate issue for tracking purposes.

**Comment by theJasonHelmick** [comment]
Great point!.  I'll take a look -- hopefully someone else will provide feedback -- but I like the idea of the default behavior to match the host, then still have the option in the config to change it.

**Comment by jdhitsolutions** [comment]
I tried a few things on this topic. The problem is that the psd1 file has to be static. This means you would have to generate the psd1 files at setup for the project. That doesn't sound  very practical. Another idea is to have some sort of script that processes essentially a list of replacement strings to generate the final psd1 files. Before running unattend, the user/author would need to manually edit (or at least review) any replacement strings first. The setup process would then dynamically generate the final psd1 files.

I like this approach as well for making it easier to set a domain name without having to manually to a search and replace through all files.

**Comment by theJasonHelmick** [comment]
This is really two different issues.  I'm going to separate them.  both our on my list.
