### ISSUE TITLE
Disable auto updating

### ISSUE THREAD

**Issue by theJasonHelmick** [pluralsight/PS-AutoLab-Env#74]
As a practice lab, this may not have much impact, but recently at a conference I ran into the issue of the VM's starting to download updates.  This caused the whole system to slow down.  I discovered how to disable the automatic updates.

This does not impact the ability to manually (or through a script) to get updates...it just prevents Windows from making the decision.  I'm interested in everyones thoughts about including the doable of automatic updates in the Config.  I believe Jeff can provide an easy way to update the VM's manually. @jdhitsolutions @majst32 

thoughts?

**Comment by majst32** [comment]
How about an option (function in the module) to turn it off if desired?

**Comment by jdhitsolutions** [comment]
Personally, I think the setup process should download and install all recommended updates for all VMs upon setup completion. We could use my post-setup script. At this point the lab is ready to go and at this point I want to disable any automatic updates. The assumption is that if I am using the lab for a course I don't want it to change midstream. Nor if I am using a lab config for a conference do I want it to update in the middle of my presentation. I think this should be the default behavior. This is a tool for creating a time-limited lab or test environment not an ongoing production network.

**Comment by majst32** [comment]
I actually thought they were patched as part of the setup process.  If that is not the case, I definitely agree with adding it.  For conference/author use - I agree with turning it off.  But for students?  What if the class they are taking is long running... or they continue to use it after the course is over ... we may be "encouraging" them by default to leave systems unpatched.  That's why I suggested making it an option - leave it on by default, make it be a conscious choice to turn it off.

**Comment by jdhitsolutions** [comment]
I don't think images are updated automatically because when I've run my Windows update script there are many updates. I think we should state that after setup the virtual servers will remain unpatched and their use is only for non-production and educational purposes. Assuming the student is also using eval copies their lab is limited anyway.

**Comment by jdhitsolutions** [comment]
The smart way to do this would be to download all updates for the different platforms and dynamically have them installed at run time. Unless Lability is already doing that but I don't think so. Otherwise servers like S1 and S2 are both downloading from Microsoft.

**Comment by themichaelbender** [comment]
I agree that downloading centrally, updating, and then turning off is the way to go.

**Comment by jdhitsolutions** [comment]
@themichaelbender I'll be looking forward to your pull request then on this.

**Comment by jdhitsolutions** [comment]
I think we could go here and download necessary update files.http://www.catalog.update.microsoft.com/Search.aspx?q=KB3194798  The trick is finding a good search technique.

**Comment by BladeFireLight** [comment]
why not just update the master copy for each OS?  If you create a childsik, run windows updates via PowerShell Direct. then either sysprep and merge if changes were made or discard if not.

**Comment by jdhitsolutions** [comment]
Once you have installed Autolab, sure you could take this approach. But this doesn't help on new installs and especially when using eval ISOs. Eventually you would need to re-create your images.

**Comment by jdhitsolutions** [comment]
I thought perhaps all we need is the latest cumulative update for Windows Server 2016. I can get that much with code like this:
```
$uri = 'http://www.catalog.update.microsoft.com/Search.aspx?q=Cumulative%20Update%20for%20Windows%20Server%202016%20for%20x64'

$r = Invoke-WebRequest $uri -DisableKeepAlive # -UseBasicParsing

$r.links.where({$_.innertext -notmatch "preview" -AND $_.innertext -match '2016'}) |
Select InnerText,@{Name="ID";Expression = {($_.id -split "_")[0]}},
@{Name="Updated";Expression={
$id = ($_.id -split "_")[0]
$d = Invoke-WebRequest "http://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=$id" -DisableKeepAlive
$t = $d.AllElements.where({$_.id -eq 'dateDiv'}).outertext
$t.split(":")[1].trim() -as [datetime]
}} | Sort Updated -Descending
```
But I can't follow through to the download link.

**Comment by theJasonHelmick** [comment]
Investigating for next release. Ideas appreciated on how best to handle this.
