### ISSUE TITLE
adding * to existing trusted hosts is invalid

### ISSUE THREAD

**Issue by BladeFireLight** [pluralsight/PS-AutoLab-Env#76]
I allrady have one trusted host (my standalone hyper-v server) so I get this error
Set-Item : WinRM cannot process the configuration request. The hostname pattern is invalid: "*" Hostname patterns must
contain one or more patterns. A pattern can contain at most one wildcard ("*"). The special pattern "<local>" can be
used to indicate all hostnames that do not have a '.'. To trust all hosts use "*" as the only pattern.
At C:\Users\Blade_000\Downloads\PS-AutoLab-Env-master\PS-AutoLab-Env-master\Setup-Host.ps1:54 char:5

While I understand the reason for *, but if the host is used for other things than just the lab like my system is, it's not a setting I'm fond of using..

**Comment by jdhitsolutions** [comment]
I totally agree and have asked about this from the beginning. Once you get Autolab installed, I'd suggest manually modifying TrustedHosts to meet your needs. The rationale behind using this setting as that we are working under the assumption that this is being setup on a temporary and testing basis and not something you would use in a production environment.

**Comment by theJasonHelmick** [comment]
Asking for code ideas to handle this. Please list here

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.

**Comment by jdhitsolutions** [comment]
I'm still not happy with the way this is handled. I'll add an enhancement issue for the new module.
