### ISSUE TITLE
Vmware Fusion

### ISSUE THREAD

**Issue by itadder** [pluralsight/PS-AutoLab-Env#77]
Would this work in VMware fusion know that Thier is POSH for mac? If not would I be able to do this from my windows VM in VMware fusion? IS DSC Supported on MACS?  I see in the youtube video your using a mac, is that through bootcamp Jason?

**Comment by jdhitsolutions** [comment]
None of this is running on the open source PowerShell. It should run any in Windows environment that supports running a Hyper-V hypervisor.

**Comment by theJasonHelmick** [comment]
AutoLab does not work with any other hyper visor than Hyper-v. The standalone configs can be used for individual VM's if desired.
