### ISSUE TITLE
Not working on server 2016 (non desktop)

### ISSUE THREAD

**Issue by BladeFireLight** [pluralsight/PS-AutoLab-Env#78]
This may be more of an issue with lability but the master hard drives do not complete correctly and result in the error , If i copy the master vhdx from windows 10 I am able to continue. 

WARNING: [3:13:54 PM] Removing incomplete image 'C:\AutoLab\MasterVirtualHardDisks\2016_x64_Standard_Core_EN_Eval.vhdx'.
WARNING: [3:13:54 PM] DSC resource 'Test-VHDTargetResource' failed with errror 'Cannot validate argument on parameter 'Genera
tion'. The argument "" does not belong to the set "Vhd,Vhdx" specified by the ValidateSet attribute. Supply an argument that 
is in the set and then try the command again.'.
WARNING: [3:13:54 PM] DSC resource 'Set-VHDTargetResource' failed with errror 'Cannot validate argument on parameter 'Generat
ion'. The argument "" does not belong to the set "Vhd,Vhdx" specified by the ValidateSet attribute. Supply an argument that i
s in the set and then try the command again.'.
WARNING: [3:13:55 PM] DSC resource 'Test-VMTargetResource' failed with errror 'Vhd 'C:\AutoLab\VMVirtualHardDisks\DC1.vhdx' d
oes not exist.'.
New-VM : Adding the device 'Microsoft:Hyper-V:Virtual Hard Disk' to 'DC1' failed.
At C:\Program 
Files\WindowsPowerShell\Modules\Lability\0.10.1\DSCResources\xHyper-V\DSCResources\MSFT_xVMHyperV\MSFT_xVMHyperV.psm1:350 
char:21
+             $null = New-VM @parameters
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.NewVM
 
Set-VM : Hyper-V was unable to find a virtual machine with name "DC1".
At C:\Program 
Files\WindowsPowerShell\Modules\Lability\0.10.1\DSCResources\xHyper-V\DSCResources\MSFT_xVMHyperV\MSFT_xVMHyperV.psm1:371 
char:21
+             $null = Set-VM @parameters
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Set-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.SetVM

**Comment by jdhitsolutions** [comment]
It is impossible to determine what you were doing to generate this error. At what point did you see this error? What operating system and PowerShell version are you running?

**Comment by BladeFireLight** [comment]
Server 2016 standard patched up to December updates, and with just the built in PowerShell.

**Comment by theJasonHelmick** [comment]
You said non desktop?  Are yo trying to run the AutoLab on Core?  AutoLab doesn't support core.
