### ISSUE TITLE
Move resources?

### ISSUE THREAD

**Issue by superdale007** [pluralsight/PS-AutoLab-Env#79]
Is there a way to move the ISO's to a different drive or even mapped drive/share? I've tired editing the HostDefaults.json file section:  "IsoPath":  "D:\\AutoLab\\ISOs" to the following with "no joy"

Mapped Drive:
"IsoPath":  "I:\\ISOs\\AutoLabISOs\\ISOs"

Network Path:
"IsoPath":  "\\batcave1\\ISOs\\AutoLabISOs\\ISOs"

Ideas?

**Comment by jdhitsolutions** [comment]
This has been a wishlist item for a while. We're partly there because you can specify the location of where to install Autolab. But I don't think we've gotten more granular than that. You might consider creating a link or junction point for the ISO folder to redirect to another location.

**Comment by jdhitsolutions** [comment]
In looking through the code I think this might work. Edit Setup-Host.ps1 and find this section:

```$DirDef = @{
    ConfigurationPath = "$DestinationPath\Configurations"
    DifferencingVhdPath = "$DestinationPath\VMVirtualHardDisks"
    HotfixPath = "$DestinationPath\Hotfixes"
    IsoPath = "$DestinationPath\ISOs"
    ModuleCachePath = "C:\ProgramData\Lability\Modules"
    ParentVhdPath = "$DestinationPath\MasterVirtualHardDisks"
    ResourcePath = "$DestinationPath\Resources"

}
```
I don't see why you couldn't hardcode a location for the ISOs. What I don't know for sure is if the downloads will go into that folder. You'll have to test.

**Comment by BladeFireLight** [comment]
A workaround would be to replace the folder with a junction.

**Comment by theJasonHelmick** [comment]
Under discussion - see issue #81
