### ISSUE TITLE
Allow custom installation

### ISSUE THREAD

**Issue by jdhitsolutions** [pluralsight/PS-AutoLab-Env#81]
There have been a number of requests for this and I think we can modify Setup-Host further. We already ask for an alternate location. We can then ask if the user would like to further customize. If so, prompt for these settings displaying the current default. It should be very easy then to customize this hashtable.

```
$DirDef = @{
    ConfigurationPath = "$DestinationPath\Configurations"
    DifferencingVhdPath = "$DestinationPath\VMVirtualHardDisks"
    HotfixPath = "$DestinationPath\Hotfixes"
    IsoPath = "$DestinationPath\ISOs"
    ModuleCachePath = "C:\ProgramData\Lability\Modules"
    ParentVhdPath = "$DestinationPath\MasterVirtualHardDisks"
    ResourcePath = "$DestinationPath\Resources"

}
```

**Comment by theJasonHelmick** [comment]
Discuss.  I'm cautious about adding complexity. Not sure why this is a needed feature.
