### ISSUE TITLE
New-LabImage : To service this Windows image requires the latest version of the DISM. See 

### ISSUE THREAD

**Issue by JustNowC** [pluralsight/PS-AutoLab-Env#82]

**Comment by theJasonHelmick** [comment]
Can you provide any other information on this?

**Comment by Tymarand** [comment]
New-LabImage : To service this Windows image requires the latest version of the DISM. See
http://go.microsoft.com/fwlink/?LinkId=293395 to find the latest version of DISM,
and http://go.microsoft.com/fwlink/?LinkId=293394 to learn how to install the latest version of DISM from the ADK on
your computer.
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.10.1\Src\LabVM.ps1:357 char:27
+ ... ef] $null = New-LabImage -Id $node.Media -ConfigurationData $Configur ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-LabImage

**Comment by Tymarand** [comment]
I have installed the ADK for Windows 10 that has DISM 10.x  I saw there was a reference to Lability having a bug when version checking under Windows 10 but I have NO idea how to implement it.  I'm new to all this, including GitHub and its inner workings.  Thank you and I hope someone can help me.

**Comment by jdhitsolutions** [comment]
This project is now under new ownership. The 3.x version line is obsolete. Version 4.0.0 has been published to the PowerShell Gallery with new updates, configuration, and documentation. It is expected that this version will resolve most if not all of the problems you were experiencing. Read [Updating](https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Updating.md) for more information.

No further action will be taken on this issue and it will most likely be closed at some point. If you still have the same issue with the new version, then go ahead and open a new issue.
