### ISSUE TITLE
Wipe-Lab Should NOT delete other configurations

### ISSUE THREAD

**Issue by jdhitsolutions** [pluralsight/PS-AutoLab-Env#87]
If you have created multiple lab configurations and run Wipe-Lab on one of them, that command kills the NAT config which might be used by other configurations and it wipes out ALL hard VDHX files, or at least tries to. This can't happen. Wipe-Lab should only remove the VM files for the virtual machines in the specific configuration.

**Comment by theJasonHelmick** [comment]
Totally agree.  Will correct in next release.
