### ISSUE TITLE
Invalid MOF definition in DevOps Fundamentals Configuration

### ISSUE THREAD

**Issue by jdhitsolutions** [pluralsight/PS-AutoLab-Env#91]
Running Server 2016 with what I think is the latest version of this project. In the DevOps Fundamentals configuration getting this error:

```
Write-NodeMOFFile : Invalid MOF definition for node 'DC1': Exception calling "ValidateInstanceText" with "1"
argument(s): "Undefined class: MSFT_RoleResource
 At line:94, char:2
 Buffer:
onName = "AutoLab";
};^
insta
"
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2369
char:21
+ ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile
```
Version info:
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jdhitsolutions** [comment]
Uninstalled the new PSDscResources module introduced in 5.1 and that seems to have removed the errors. There is a duplication of core resources like WindowFeature between PSDesiredStateConfiguration and PSDscResources. We may need to revise configs for PowerShell 5.1 and this new module because this is the direction the PowerShell DSC team is headed.

**Comment by majst32** [comment]
PSDSCResources does overwrite the in-box resources per their notes in GitHub.  PSDSCResources only runs on 5.1 from what I recall.

**Comment by theJasonHelmick** [comment]
I just love all the random breaking updates.  This is going to be addressed in the new version under development. Will leave this issue open for testing.
