### ISSUE TITLE
Proposed Revisions

### ISSUE THREAD

**Issue by jdhitsolutions** [pluralsight/PS-AutoLab-Env#92]
I think this project should address these points in the next major revision, which will definitely be breaking changes.

1. Take a dependency on PowerShell 5.1
2. Modify configurations to use PSDscResources instead of PSDesiredStateConfiguration
3. Re-organize configuration data per Missy's suggestions
4. Functions in PSAutolab should have standard names. Use existing names as aliases.

**Comment by theJasonHelmick** [comment]
1-3 is on the dev list I'm working on now for the next version. 4. is a challenge as there are conflicts with Lability, but I agree and will attempt to resolve.

**Comment by jdhitsolutions** [comment]
The naming issue should be easy to resolve - use a prefix for the autolab commands. Perhaps AL or PSAL. Then, as I've suggested before, create aliases so the setup scripts don't break.
